export type Scholarship = {
  id: string;
  name: string;
  provider: string;
  country: string;
  majors: string[];
  amount: string;
  deadline: string;
  level: "undergraduate" | "graduate" | "both";
  fullRide: boolean;
  tags: string[];
  summary: string;
};

export const COUNTRIES = [
  "United States",
  "United Kingdom",
  "Canada",
  "Germany",
  "Australia",
  "Japan",
  "South Korea",
  "Netherlands",
  "Singapore",
  "Switzerland",
  "France",
  "Sweden",
  "Denmark",
  "Italy",
  "Spain",
  "Ireland",
  "Hong Kong",
  "China",
  "Belgium",
  "Norway",
  "United Arab Emirates",
  "Saudi Arabia",
  "Israel",
  "Qatar",
  "Turkey",
  "India",
  "Malaysia",
  "Thailand",
  "Indonesia",
  "Philippines",
  "Vietnam",
  "South Africa",
  "Egypt",
  "Morocco",
  "Kenya",
  "Rwanda",
  "Brazil",
  "Mexico",
  "Argentina",
  "Chile",
  "Colombia",
  "Taiwan",
  "New Zealand",
  "Austria",
];

export const MAJORS = [
  "Computer Science",
  "Engineering",
  "Business",
  "Economics",
  "Mathematics",
  "Physics",
  "Biology",
  "Medicine",
  "Law",
  "Political Science",
  "International Relations",
  "Liberal Arts",
  "Architecture",
  "Design",
  "Environmental Science",
];

export const SCHOLARSHIPS: Scholarship[] = [
  {
    id: "harvard-finaid",
    name: "Harvard Financial Aid Initiative",
    provider: "Harvard University",
    country: "United States",
    majors: ["Computer Science", "Economics", "Liberal Arts", "Mathematics", "Physics", "Biology"],
    amount: "Full tuition + room & board",
    deadline: "Jan 1, 2027",
    level: "undergraduate",
    fullRide: true,
    tags: ["need-based", "ivy", "full-ride", "high-sat", "international-friendly"],
    summary:
      "Need-based grant covering 100% of demonstrated financial need for admitted students from any country. Families earning under $85K pay nothing.",
  },
  {
    id: "mit-need",
    name: "MIT Need-Based Aid",
    provider: "Massachusetts Institute of Technology",
    country: "United States",
    majors: ["Computer Science", "Engineering", "Mathematics", "Physics"],
    amount: "Up to $80,000 / year",
    deadline: "Feb 15, 2027",
    level: "undergraduate",
    fullRide: true,
    tags: ["need-based", "stem", "research", "high-sat", "international-friendly"],
    summary:
      "MIT meets 100% of demonstrated need with grants — no loans. Open to students worldwide pursuing STEM-focused degrees.",
  },
  {
    id: "stanford-knight-hennessy",
    name: "Knight-Hennessy Scholars",
    provider: "Stanford University",
    country: "United States",
    majors: ["Business", "Engineering", "Law", "Medicine", "Computer Science", "Economics"],
    amount: "Full graduate tuition + stipend",
    deadline: "Oct 11, 2026",
    level: "graduate",
    fullRide: true,
    tags: ["leadership", "graduate", "full-ride", "merit", "international-friendly"],
    summary:
      "Up to three years of full funding for graduate study at Stanford with a leadership development program. 100 scholars per year.",
  },
  {
    id: "yale-finaid",
    name: "Yale International Aid",
    provider: "Yale University",
    country: "United States",
    majors: ["Liberal Arts", "Political Science", "Economics", "International Relations", "Law"],
    amount: "Full demonstrated need",
    deadline: "Jan 2, 2027",
    level: "undergraduate",
    fullRide: true,
    tags: ["need-based", "ivy", "international-friendly", "full-ride"],
    summary:
      "Yale is need-blind for all applicants including international students. Average aid award: $66,000/year.",
  },
  {
    id: "princeton-finaid",
    name: "Princeton Aid for International Students",
    provider: "Princeton University",
    country: "United States",
    majors: ["Mathematics", "Physics", "Economics", "Computer Science", "Liberal Arts", "Engineering"],
    amount: "Full need + no loans",
    deadline: "Jan 1, 2027",
    level: "undergraduate",
    fullRide: true,
    tags: ["need-based", "ivy", "full-ride", "international-friendly"],
    summary:
      "Princeton replaced loans with grants. Aid covers full demonstrated need including travel, books, and personal expenses.",
  },
  {
    id: "columbia-finaid",
    name: "Columbia Need-Based Aid",
    provider: "Columbia University",
    country: "United States",
    majors: ["Business", "Engineering", "International Relations", "Liberal Arts", "Law"],
    amount: "Up to full tuition",
    deadline: "Jan 1, 2027",
    level: "undergraduate",
    fullRide: true,
    tags: ["need-based", "ivy", "international-friendly", "high-sat"],
    summary:
      "Need-blind admission for all applicants. 100% of need met with grants and work-study; no loans required.",
  },
  {
    id: "fulbright",
    name: "Fulbright Foreign Student Program",
    provider: "U.S. Department of State",
    country: "United States",
    majors: ["International Relations", "Political Science", "Economics", "Liberal Arts", "Engineering", "Medicine"],
    amount: "Tuition + living + travel",
    deadline: "May 15, 2027",
    level: "graduate",
    fullRide: true,
    tags: ["government", "graduate", "leadership", "international-friendly"],
    summary:
      "Prestigious U.S. government scholarship for graduate study. Covers tuition, books, airfare, health insurance, and a living stipend.",
  },
  {
    id: "brown-finaid",
    name: "Brown University Need-Based Financial Aid",
    provider: "Brown University",
    country: "United States",
    majors: ["Computer Science", "Engineering", "Liberal Arts", "Economics", "International Relations"],
    amount: "Full demonstrated need (up to ~$90,000/year)",
    deadline: "Jan 3, 2027",
    level: "undergraduate",
    fullRide: false,
    tags: ["need-based", "ivy", "international-friendly", "prestigious"],
    summary:
      "Brown meets 100% of demonstrated financial need for admitted international undergraduates through its need-blind aid program, with no loans in aid packages for families below set income thresholds.",
  },
  {
    id: "upenn-finaid",
    name: "Penn International Student Financial Aid",
    provider: "University of Pennsylvania",
    country: "United States",
    majors: ["Business", "Economics", "Engineering", "Computer Science", "Liberal Arts"],
    amount: "Full demonstrated need (avg ~$65,000/year)",
    deadline: "Jan 5, 2027",
    level: "undergraduate",
    fullRide: false,
    tags: ["need-based", "ivy", "international-friendly", "prestigious"],
    summary:
      "Penn admits international undergraduates need-blind and meets 100% of demonstrated need with grant-based aid, replacing loans with scholarship funds for all qualifying students.",
  },
  {
    id: "cornell-tata",
    name: "Tata Scholarship for Students from India",
    provider: "Cornell University",
    country: "United States",
    majors: ["Engineering", "Computer Science", "Business", "Economics", "Architecture"],
    amount: "Up to full tuition and fees (~$70,000/year)",
    deadline: "Jan 2, 2027",
    level: "undergraduate",
    fullRide: false,
    tags: ["need-based", "ivy", "international-friendly", "prestigious", "high-sat"],
    summary:
      "Endowed by the Tata Education and Development Trust, this fund supports up to 20 Indian undergraduates at Cornell each year with substantial need-based aid covering tuition, room, and board.",
  },
  {
    id: "dartmouth-finaid",
    name: "Dartmouth International Need-Based Aid",
    provider: "Dartmouth College",
    country: "United States",
    majors: ["Liberal Arts", "Economics", "Engineering", "Political Science", "Environmental Science"],
    amount: "Full demonstrated need (up to ~$87,000/year)",
    deadline: "Jan 3, 2027",
    level: "undergraduate",
    fullRide: false,
    tags: ["need-based", "ivy", "international-friendly", "prestigious"],
    summary:
      "Dartmouth is one of a handful of U.S. colleges that is need-blind for international applicants and meets 100% of demonstrated need with no-loan aid packages funded by its endowment.",
  },
  {
    id: "uchicago-odyssey",
    name: "Odyssey Scholarship",
    provider: "University of Chicago",
    country: "United States",
    majors: ["Economics", "Mathematics", "Physics", "Computer Science", "Liberal Arts"],
    amount: "Full tuition + summer stipend",
    deadline: "Jan 5, 2027",
    level: "undergraduate",
    fullRide: true,
    tags: ["need-based", "full-ride", "international-friendly", "prestigious", "high-sat"],
    summary:
      "UChicago's Odyssey program eliminates loans and guarantees free tuition for admitted students from middle- and lower-income families, including international applicants, plus paid summer internships.",
  },
  {
    id: "duke-karsh",
    name: "Karsh International Scholars Program",
    provider: "Duke University",
    country: "United States",
    majors: ["Engineering", "Computer Science", "Economics", "Political Science", "International Relations"],
    amount: "Full need + research and travel stipends",
    deadline: "Jan 3, 2027",
    level: "undergraduate",
    fullRide: true,
    tags: ["need-based", "merit", "full-ride", "international-friendly", "research", "prestigious", "high-sat"],
    summary:
      "Duke's flagship Karsh program selects exceptional international undergraduates for full need-based aid plus dedicated funding for summer research, conferences, and global experiences across all four years.",
  },
  {
    id: "northwestern-finaid",
    name: "Northwestern International Financial Aid",
    provider: "Northwestern University",
    country: "United States",
    majors: ["Engineering", "Business", "Economics", "Computer Science", "Liberal Arts"],
    amount: "Full demonstrated need (up to ~$85,000/year)",
    deadline: "Jan 2, 2027",
    level: "undergraduate",
    fullRide: false,
    tags: ["need-based", "international-friendly", "prestigious"],
    summary:
      "Northwestern admits international students need-aware but commits to meeting 100% of demonstrated financial need for all admitted international undergraduates with no-loan aid packages.",
  },
  {
    id: "caltech-finaid",
    name: "Caltech Need-Based Scholarships",
    provider: "California Institute of Technology",
    country: "United States",
    majors: ["Physics", "Mathematics", "Computer Science", "Engineering", "Biology"],
    amount: "Full demonstrated need (avg ~$55,000/year)",
    deadline: "Jan 3, 2027",
    level: "undergraduate",
    fullRide: false,
    tags: ["need-based", "stem", "international-friendly", "research", "prestigious", "high-sat"],
    summary:
      "Caltech meets 100% of demonstrated need for international undergraduates admitted to its rigorous STEM programs, with aid packages built primarily from institutional grants rather than loans.",
  },
  {
    id: "jhu-hodson",
    name: "Hodson Trust Scholarship",
    provider: "Johns Hopkins University",
    country: "United States",
    majors: ["Biology", "Medicine", "Engineering", "Computer Science", "Physics"],
    amount: "Up to $40,000/year",
    deadline: "Jan 2, 2027",
    level: "undergraduate",
    fullRide: false,
    tags: ["merit", "stem", "international-friendly", "research", "prestigious", "high-sat"],
    summary:
      "Johns Hopkins awards the prestigious Hodson Trust Scholarship to a small cohort of incoming undergraduates, including internationals, based on outstanding academic achievement and leadership potential.",
  },
  {
    id: "nyu-anbryce",
    name: "AnBryce Scholarship",
    provider: "New York University",
    country: "United States",
    majors: ["Liberal Arts", "Business", "Economics", "Political Science", "Law"],
    amount: "Full tuition + academic enrichment stipend",
    deadline: "Jan 5, 2027",
    level: "undergraduate",
    fullRide: true,
    tags: ["need-based", "merit", "full-ride", "international-friendly", "leadership", "prestigious"],
    summary:
      "NYU's AnBryce Scholarship offers full tuition to first-generation college students, including eligible international applicants, paired with mentorship, research funding, and global learning experiences.",
  },
  {
    id: "usc-trustee",
    name: "USC Trustee Scholarship",
    provider: "University of Southern California",
    country: "United States",
    majors: ["Computer Science", "Engineering", "Business", "Design", "Architecture"],
    amount: "Full tuition (~$68,000/year)",
    deadline: "Dec 1, 2026",
    level: "undergraduate",
    fullRide: false,
    tags: ["merit", "international-friendly", "prestigious", "high-sat", "leadership"],
    summary:
      "USC's Trustee Scholarship covers full tuition for four years and is awarded to a select group of incoming freshmen, including international students, based on exceptional academic and personal achievement.",
  },
  {
    id: "amherst-finaid",
    name: "Amherst College Need-Blind International Aid",
    provider: "Amherst College",
    country: "United States",
    majors: ["Liberal Arts", "Economics", "Mathematics", "Political Science", "Environmental Science"],
    amount: "Full demonstrated need (up to ~$88,000/year)",
    deadline: "Jan 3, 2027",
    level: "undergraduate",
    fullRide: false,
    tags: ["need-based", "international-friendly", "prestigious", "high-sat"],
    summary:
      "Amherst is one of only a few U.S. liberal arts colleges that is fully need-blind for international applicants and meets 100% of demonstrated need with grant-only, loan-free financial aid packages.",
  },
  {
    id: "rhodes",
    name: "Rhodes Scholarship",
    provider: "Rhodes Trust",
    country: "United Kingdom",
    majors: ["Liberal Arts", "Political Science", "Law", "International Relations", "Economics", "Medicine"],
    amount: "Full tuition + £18,180 stipend",
    deadline: "Sep 1, 2026",
    level: "graduate",
    fullRide: true,
    tags: ["leadership", "graduate", "full-ride", "merit", "prestigious"],
    summary:
      "World's oldest international fellowship for graduate study at Oxford. Highly selective — about 100 scholars elected per year.",
  },
  {
    id: "chevening",
    name: "Chevening Scholarship",
    provider: "UK Government / FCDO",
    country: "United Kingdom",
    majors: ["International Relations", "Political Science", "Economics", "Business", "Law", "Environmental Science"],
    amount: "Full tuition + monthly stipend",
    deadline: "Nov 5, 2026",
    level: "graduate",
    fullRide: true,
    tags: ["government", "graduate", "leadership", "international-friendly", "full-ride"],
    summary:
      "UK government's global scholarship for one-year master's programs. Open to applicants from over 160 countries.",
  },
  {
    id: "gates-cambridge",
    name: "Gates Cambridge Scholarship",
    provider: "Bill & Melinda Gates Foundation",
    country: "United Kingdom",
    majors: ["Computer Science", "Engineering", "Medicine", "Mathematics", "Biology", "Physics", "Environmental Science"],
    amount: "Full cost of study",
    deadline: "Dec 3, 2026",
    level: "graduate",
    fullRide: true,
    tags: ["graduate", "full-ride", "merit", "research", "prestigious"],
    summary:
      "Full-cost scholarship for outstanding international students to pursue postgraduate study at Cambridge. ~80 awards per year.",
  },
  {
    id: "clarendon",
    name: "Clarendon Fund Scholarships",
    provider: "University of Oxford",
    country: "United Kingdom",
    majors: ["Liberal Arts", "Mathematics", "Physics", "Computer Science", "Law", "Economics", "Medicine"],
    amount: "Full fees + living grant",
    deadline: "Jan 8, 2027",
    level: "graduate",
    fullRide: true,
    tags: ["graduate", "merit", "full-ride", "research"],
    summary:
      "Oxford's flagship graduate scholarship — over 200 scholarships awarded annually to applicants of any nationality.",
  },
  {
    id: "reach-oxford",
    name: "Reach Oxford Scholarship",
    provider: "University of Oxford",
    country: "United Kingdom",
    majors: ["Liberal Arts", "Economics", "Political Science", "Mathematics", "Engineering"],
    amount: "Full tuition + £15,500/year stipend",
    deadline: "Feb 5, 2027",
    level: "undergraduate",
    fullRide: true,
    tags: ["need-based", "merit", "full-ride", "international-friendly", "high-sat", "prestigious"],
    summary:
      "Covers tuition, college fees, and living costs at Oxford for talented students from low-income countries who cannot otherwise afford an overseas education.",
  },
  {
    id: "cambridge-trust",
    name: "Cambridge Trust International Scholarship",
    provider: "Cambridge Trust",
    country: "United Kingdom",
    majors: ["Computer Science", "Engineering", "Mathematics", "Physics", "Medicine", "Law"],
    amount: "Up to £45,000/year (full cost)",
    deadline: "Dec 5, 2026",
    level: "both",
    fullRide: true,
    tags: ["merit", "full-ride", "international-friendly", "prestigious", "high-sat"],
    summary:
      "Awarded jointly with Cambridge admission, the Trust covers full tuition plus maintenance for outstanding international students across nearly every discipline.",
  },
  {
    id: "marshall",
    name: "Marshall Scholarship",
    provider: "Marshall Aid Commemoration Commission",
    country: "United Kingdom",
    majors: ["Political Science", "International Relations", "Economics", "Law", "Engineering", "Physics"],
    amount: "Full tuition + ~£18,000/year stipend",
    deadline: "Sep 29, 2026",
    level: "graduate",
    fullRide: true,
    tags: ["merit", "full-ride", "leadership", "graduate", "government", "prestigious"],
    summary:
      "Funds up to two years of graduate study at any UK university for high-achieving American students with proven leadership and academic distinction.",
  },
  {
    id: "daad",
    name: "DAAD Scholarships",
    provider: "German Academic Exchange Service",
    country: "Germany",
    majors: ["Engineering", "Computer Science", "Business", "Architecture", "Environmental Science", "Mathematics", "Physics"],
    amount: "€934/mo + tuition coverage",
    deadline: "Oct 31, 2026",
    level: "both",
    fullRide: false,
    tags: ["government", "international-friendly", "research", "stem"],
    summary:
      "Germany's largest funding organization for international students. Wide range of programs for undergrad, master's, PhD, and research stays.",
  },
  {
    id: "tu-munich-deutschland",
    name: "Deutschlandstipendium",
    provider: "TU Munich & partner universities",
    country: "Germany",
    majors: ["Engineering", "Computer Science", "Mathematics", "Physics", "Business"],
    amount: "€300/mo (no tuition needed)",
    deadline: "Apr 30, 2027",
    level: "undergraduate",
    fullRide: false,
    tags: ["merit", "stem", "international-friendly"],
    summary:
      "Merit-based monthly stipend at participating German universities. Pairs with Germany's already tuition-free public universities.",
  },
  {
    id: "humboldt-research",
    name: "Humboldt Research Fellowship",
    provider: "Alexander von Humboldt Foundation",
    country: "Germany",
    majors: ["Physics", "Biology", "Computer Science", "Engineering", "Mathematics"],
    amount: "€2,750–3,250/month + research allowance",
    deadline: "Oct 15, 2026",
    level: "graduate",
    fullRide: true,
    tags: ["merit", "full-ride", "research", "graduate", "stem", "prestigious", "language-training"],
    summary:
      "Hosts top postdoctoral researchers worldwide for 6–24 months at any German institution, with a generous monthly stipend, family allowances, and free German language training.",
  },
  {
    id: "holland",
    name: "Holland Scholarship",
    provider: "Dutch Ministry of Education",
    country: "Netherlands",
    majors: ["Business", "Engineering", "Design", "Architecture", "Economics", "Environmental Science"],
    amount: "€5,000 (one-time)",
    deadline: "Feb 1, 2027",
    level: "both",
    fullRide: false,
    tags: ["government", "international-friendly", "merit"],
    summary:
      "One-time award for non-EEA international students starting at participating Dutch research universities or universities of applied sciences.",
  },
  {
    id: "erasmus-mundus-jmd",
    name: "Erasmus Mundus Joint Masters",
    provider: "European Commission",
    country: "Netherlands",
    majors: ["Computer Science", "Environmental Science", "Engineering", "International Relations", "Economics"],
    amount: "€1,400/month + tuition + travel",
    deadline: "Jan 15, 2027",
    level: "graduate",
    fullRide: true,
    tags: ["merit", "full-ride", "international-friendly", "research", "graduate", "government", "prestigious"],
    summary:
      "Two-year master's programs delivered jointly by consortia of European universities, with full tuition, monthly stipend, and travel allowance for top global applicants.",
  },
  {
    id: "ethz-excellence",
    name: "ETH Excellence Scholarship",
    provider: "ETH Zurich",
    country: "Switzerland",
    majors: ["Engineering", "Computer Science", "Mathematics", "Physics", "Architecture", "Environmental Science"],
    amount: "CHF 12,000/sem + tuition waiver",
    deadline: "Dec 15, 2026",
    level: "graduate",
    fullRide: true,
    tags: ["merit", "graduate", "stem", "research", "full-ride"],
    summary:
      "Full grant covering living and study expenses for outstanding master's students at ETH Zurich. Highly selective — top 5% of applicants.",
  },
  {
    id: "epfl-excellence",
    name: "EPFL Excellence Fellowships",
    provider: "École polytechnique fédérale de Lausanne",
    country: "Switzerland",
    majors: ["Engineering", "Computer Science", "Mathematics", "Physics", "Architecture"],
    amount: "CHF 16,000/yr + tuition",
    deadline: "Dec 15, 2026",
    level: "graduate",
    fullRide: false,
    tags: ["merit", "graduate", "stem", "research"],
    summary:
      "Merit-based fellowship for incoming master's students at EPFL. Awarded to candidates with outstanding academic records.",
  },
  {
    id: "eiffel-excellence",
    name: "Eiffel Excellence Scholarship",
    provider: "Campus France",
    country: "France",
    majors: ["Engineering", "Economics", "Law", "Political Science", "International Relations"],
    amount: "€1,181–1,700/month + travel + insurance",
    deadline: "Jan 10, 2027",
    level: "graduate",
    fullRide: false,
    tags: ["merit", "international-friendly", "graduate", "government", "prestigious"],
    summary:
      "Flagship French government award attracting top foreign master's and PhD students to French institutions, with monthly stipend, return airfare, and health coverage.",
  },
  {
    id: "swedish-institute-gp",
    name: "Swedish Institute Scholarships for Global Professionals",
    provider: "Swedish Institute",
    country: "Sweden",
    majors: ["Environmental Science", "Engineering", "Political Science", "Business", "International Relations"],
    amount: "Full tuition + SEK 12,000/month",
    deadline: "Feb 12, 2027",
    level: "graduate",
    fullRide: true,
    tags: ["merit", "full-ride", "leadership", "international-friendly", "graduate", "government"],
    summary:
      "Funds full master's studies in Sweden for emerging leaders from selected developing countries, covering tuition, living costs, insurance, and a one-time travel grant.",
  },
  {
    id: "danish-government-cultural",
    name: "Danish Government Scholarships under the Cultural Agreements",
    provider: "Danish Ministry of Higher Education and Science",
    country: "Denmark",
    majors: ["Design", "Architecture", "Liberal Arts", "Environmental Science", "Political Science"],
    amount: "DKK 8,243/month + tuition waiver",
    deadline: "Mar 1, 2027",
    level: "both",
    fullRide: false,
    tags: ["merit", "international-friendly", "government", "language-training"],
    summary:
      "Offered to students from countries with cultural agreements with Denmark, providing a monthly living stipend, tuition exemption, and access to free Danish language courses.",
  },
  {
    id: "italian-government-mae",
    name: "Italian Government MAECI Scholarship",
    provider: "Italian Ministry of Foreign Affairs",
    country: "Italy",
    majors: ["Architecture", "Design", "Liberal Arts", "Political Science", "Economics"],
    amount: "€900/month + tuition waiver",
    deadline: "Jun 9, 2026",
    level: "graduate",
    fullRide: false,
    tags: ["merit", "international-friendly", "graduate", "government", "language-training"],
    summary:
      "Supports foreign and Italian-descent students pursuing master's, PhD, or Italian language courses in Italy, with a monthly allowance, tuition exemption, and health insurance.",
  },
  {
    id: "fundacion-carolina",
    name: "Fundación Carolina Postgraduate Scholarship",
    provider: "Fundación Carolina",
    country: "Spain",
    majors: ["Economics", "Business", "Law", "International Relations", "Political Science"],
    amount: "Full tuition + €1,200/month",
    deadline: "Feb 28, 2027",
    level: "graduate",
    fullRide: true,
    tags: ["merit", "full-ride", "international-friendly", "graduate", "prestigious"],
    summary:
      "Premier Spanish award funding Latin American and select international students to complete master's programs at top Spanish universities, with full tuition, living costs, and travel.",
  },
  {
    id: "trinity-college-dublin-global",
    name: "Trinity College Dublin Global Excellence Scholarship",
    provider: "Trinity College Dublin",
    country: "Ireland",
    majors: ["Computer Science", "Business", "Engineering", "Law", "Liberal Arts"],
    amount: "€5,000–25,000/year",
    deadline: "Apr 30, 2027",
    level: "both",
    fullRide: false,
    tags: ["merit", "international-friendly", "high-sat", "prestigious"],
    summary:
      "Awarded automatically to top-ranking non-EU applicants admitted to Trinity, providing partial tuition reductions for the duration of an undergraduate or master's degree.",
  },
  {
    id: "government-of-ireland-ihea",
    name: "Government of Ireland International Education Scholarship",
    provider: "Higher Education Authority of Ireland",
    country: "Ireland",
    majors: ["Engineering", "Computer Science", "Environmental Science", "Business", "Medicine"],
    amount: "€10,000 + full tuition waiver",
    deadline: "Mar 26, 2027",
    level: "both",
    fullRide: false,
    tags: ["merit", "international-friendly", "government", "prestigious"],
    summary:
      "Competitive one-year award for non-EU/EEA students at any publicly funded Irish higher education institution, combining a full fee waiver with a €10,000 stipend.",
  },
  {
    id: "vanier",
    name: "Vanier Canada Graduate Scholarships",
    provider: "Government of Canada",
    country: "Canada",
    majors: ["Engineering", "Computer Science", "Medicine", "Biology", "Physics", "Mathematics", "Environmental Science"],
    amount: "CAD $50,000 / year × 3 yrs",
    deadline: "Nov 1, 2026",
    level: "graduate",
    fullRide: true,
    tags: ["government", "graduate", "research", "merit", "stem"],
    summary:
      "Attracts world-class doctoral students to Canadian universities. CAD $150,000 over three years for PhD studies.",
  },
  {
    id: "uoft-lester-pearson",
    name: "Lester B. Pearson International Scholarship",
    provider: "University of Toronto",
    country: "Canada",
    majors: ["Computer Science", "Engineering", "Business", "Liberal Arts", "Economics", "Medicine"],
    amount: "Full tuition + books + living",
    deadline: "Nov 30, 2026",
    level: "undergraduate",
    fullRide: true,
    tags: ["merit", "international-friendly", "full-ride", "leadership"],
    summary:
      "U of T's most prestigious undergrad award for international students. Covers tuition, books, incidental fees, and full residence support for four years.",
  },
  {
    id: "mcgill-entrance",
    name: "McGill Entrance Scholarship Program",
    provider: "McGill University",
    country: "Canada",
    majors: ["Computer Science", "Engineering", "Medicine", "Law", "Liberal Arts"],
    amount: "CAD $3,000–$12,000/year",
    deadline: "Jan 21, 2027",
    level: "undergraduate",
    fullRide: false,
    tags: ["merit", "high-sat", "international-friendly", "prestigious"],
    summary:
      "McGill's flagship merit awards for top first-year entrants — one-time entrance prizes to renewable major scholarships covering a substantial share of tuition for standout SAT and IB performers.",
  },
  {
    id: "ubc-ilot",
    name: "International Leader of Tomorrow Award",
    provider: "University of British Columbia",
    country: "Canada",
    majors: ["Business", "Engineering", "Environmental Science", "Political Science", "Computer Science"],
    amount: "Up to CAD $80,000/year (full need)",
    deadline: "Nov 15, 2026",
    level: "undergraduate",
    fullRide: true,
    tags: ["need-based", "merit", "leadership", "international-friendly", "full-ride", "prestigious"],
    summary:
      "UBC's signature award for international undergraduates combines demonstrated financial need with superior academic achievement and leadership, covering tuition, fees, and living costs in Vancouver.",
  },
  {
    id: "waterloo-president",
    name: "President's Scholarship of Distinction",
    provider: "University of Waterloo",
    country: "Canada",
    majors: ["Computer Science", "Engineering", "Mathematics", "Physics"],
    amount: "CAD $2,000 + research/exchange grants",
    deadline: "Feb 1, 2027",
    level: "undergraduate",
    fullRide: false,
    tags: ["merit", "high-sat", "stem", "research", "international-friendly"],
    summary:
      "Awarded to incoming Waterloo students entering with averages of 95%+ or equivalent SAT scores, paired with a guaranteed research or international exchange experience grant during the co-op degree.",
  },
  {
    id: "australia-awards",
    name: "Australia Awards Scholarships",
    provider: "Australian Government",
    country: "Australia",
    majors: ["Engineering", "Environmental Science", "Medicine", "Business", "Economics", "Political Science"],
    amount: "Full tuition + travel + AUD $31,000 stipend",
    deadline: "Apr 30, 2027",
    level: "both",
    fullRide: true,
    tags: ["government", "full-ride", "international-friendly", "leadership"],
    summary:
      "Australian government scholarship for students from developing countries. Full tuition, return airfare, establishment allowance, and stipend.",
  },
  {
    id: "anu-chancellor",
    name: "ANU Chancellor's International Scholarship",
    provider: "Australian National University",
    country: "Australia",
    majors: ["Computer Science", "Engineering", "International Relations", "Economics", "Physics", "Mathematics"],
    amount: "AUD $25,000 per year",
    deadline: "Oct 31, 2026",
    level: "undergraduate",
    fullRide: false,
    tags: ["merit", "international-friendly", "high-sat"],
    summary:
      "Tuition fee reduction for high-achieving international undergraduates. Renewable for the duration of the degree if academic standing is maintained.",
  },
  {
    id: "sydney-india-equity",
    name: "Sydney Scholars India Equity Scholarship",
    provider: "University of Sydney",
    country: "Australia",
    majors: ["Engineering", "Business", "Architecture", "Liberal Arts", "Law"],
    amount: "AUD $40,000 (one-off)",
    deadline: "Oct 31, 2026",
    level: "undergraduate",
    fullRide: false,
    tags: ["merit", "need-based", "international-friendly", "prestigious"],
    summary:
      "A one-time tuition offset awarded to high-achieving international undergraduates joining USyd, prioritizing students whose academic records and SAT or A-Level results place them in the top tier of applicants.",
  },
  {
    id: "melbourne-international",
    name: "Melbourne International Undergraduate Scholarship",
    provider: "University of Melbourne",
    country: "Australia",
    majors: ["Liberal Arts", "Economics", "Biology", "Design", "Environmental Science"],
    amount: "AUD $10,000–full tuition",
    deadline: "Dec 31, 2026",
    level: "undergraduate",
    fullRide: true,
    tags: ["merit", "high-sat", "full-ride", "international-friendly", "prestigious"],
    summary:
      "Tiered awards for international entrants to Melbourne's signature generalist degrees, with the top band covering 100% of tuition for the full three years for applicants with exceptional SAT and entrance scores.",
  },
  {
    id: "unsw-global",
    name: "UNSW Global Academic Award",
    provider: "University of New South Wales",
    country: "Australia",
    majors: ["Engineering", "Computer Science", "Business", "Mathematics"],
    amount: "AUD $20,000/year",
    deadline: "Nov 30, 2026",
    level: "undergraduate",
    fullRide: false,
    tags: ["merit", "high-sat", "stem", "international-friendly"],
    summary:
      "Automatic consideration for high-achieving international applicants to UNSW Sydney, rewarding strong SAT, ATAR, or equivalent entry credentials with a renewable contribution toward tuition in Kensington.",
  },
  {
    id: "mext",
    name: "MEXT Scholarship",
    provider: "Japanese Government",
    country: "Japan",
    majors: ["Engineering", "Computer Science", "Mathematics", "Physics", "Architecture", "Design", "Environmental Science"],
    amount: "Full tuition + ¥117,000/mo + airfare",
    deadline: "May 31, 2027",
    level: "both",
    fullRide: true,
    tags: ["government", "full-ride", "international-friendly", "research"],
    summary:
      "Japanese government's flagship scholarship. Fully funded undergraduate, master's, and research programs at Japanese universities.",
  },
  {
    id: "todai-globe",
    name: "GlobE Scholarship for PEAK Students",
    provider: "University of Tokyo",
    country: "Japan",
    majors: ["International Relations", "Environmental Science", "Liberal Arts", "Political Science"],
    amount: "¥1,200,000/year + tuition waiver",
    deadline: "Dec 9, 2026",
    level: "undergraduate",
    fullRide: true,
    tags: ["merit", "full-ride", "international-friendly", "prestigious", "high-sat"],
    summary:
      "Awarded to top admits of UTokyo's English-medium PEAK program in Komaba, covering tuition plus a monthly stipend for students pursuing International Programs on Japan and East Asia or Environmental Sciences.",
  },
  {
    id: "kyoto-iup",
    name: "Kyoto iUP Scholarship",
    provider: "Kyoto University",
    country: "Japan",
    majors: ["Engineering", "Physics", "Biology", "Economics", "Liberal Arts"],
    amount: "Full tuition + ¥120,000/month + airfare",
    deadline: "Nov 7, 2026",
    level: "undergraduate",
    fullRide: true,
    tags: ["full-ride", "merit", "language-training", "international-friendly", "prestigious", "government"],
    summary:
      "Kyoto University's flagship International Undergraduate Program funds a six-month preparatory year of intensive Japanese followed by a full Japanese-language degree, with stipend, airfare, and tuition fully covered.",
  },
  {
    id: "waseda-tuition",
    name: "Waseda University Tuition Reduction Scholarship",
    provider: "Waseda University",
    country: "Japan",
    majors: ["Political Science", "Economics", "International Relations", "Liberal Arts", "Business"],
    amount: "50–100% tuition reduction",
    deadline: "Feb 15, 2027",
    level: "undergraduate",
    fullRide: false,
    tags: ["merit", "need-based", "international-friendly"],
    summary:
      "Pre-arrival award for international entrants to Waseda's English-track SILS, PSE, and SPSE programs in Tokyo, slashing annual tuition by half or in full based on combined academic and financial review.",
  },
  {
    id: "kgsp",
    name: "Korean Government Scholarship Program",
    provider: "Korean Government / NIIED",
    country: "South Korea",
    majors: ["Engineering", "Computer Science", "Business", "Design", "Liberal Arts", "International Relations"],
    amount: "Tuition + ₩1,000,000/mo + airfare",
    deadline: "Mar 15, 2027",
    level: "both",
    fullRide: true,
    tags: ["government", "full-ride", "international-friendly", "language-training"],
    summary:
      "Full scholarship at top Korean universities including a year of Korean language training. Competitive selection through embassies.",
  },
  {
    id: "kaist-international",
    name: "KAIST International Student Scholarship",
    provider: "KAIST",
    country: "South Korea",
    majors: ["Computer Science", "Engineering", "Mathematics", "Physics", "Biology"],
    amount: "Full tuition + ₩350,000/month",
    deadline: "Sep 30, 2026",
    level: "undergraduate",
    fullRide: true,
    tags: ["full-ride", "merit", "stem", "research", "international-friendly", "prestigious"],
    summary:
      "KAIST waives full tuition and provides a monthly living stipend to admitted international undergraduates in Daejeon, with renewal contingent on maintaining a strong GPA across the four-year STEM curriculum.",
  },
  {
    id: "asean-singapore",
    name: "ASEAN Undergraduate Scholarship (NUS)",
    provider: "National University of Singapore",
    country: "Singapore",
    majors: ["Computer Science", "Engineering", "Business", "Economics", "Mathematics", "Medicine"],
    amount: "Tuition + S$5,800 living allowance",
    deadline: "Mar 19, 2027",
    level: "undergraduate",
    fullRide: false,
    tags: ["merit", "international-friendly", "stem", "high-sat"],
    summary:
      "Tuition coverage and annual living stipend for undergraduates from ASEAN countries (excluding Singapore) admitted to NUS.",
  },
  {
    id: "ntu-nanyang",
    name: "Nanyang Scholarship",
    provider: "Nanyang Technological University",
    country: "Singapore",
    majors: ["Engineering", "Computer Science", "Business", "Design", "Environmental Science"],
    amount: "Full tuition + S$6,500/year + accommodation",
    deadline: "Mar 19, 2027",
    level: "undergraduate",
    fullRide: true,
    tags: ["full-ride", "merit", "leadership", "high-sat", "prestigious"],
    summary:
      "NTU Singapore's most prestigious undergraduate award covers tuition, an annual living allowance, hostel fees, and an overseas exchange grant for students with outstanding SATs and demonstrated leadership.",
  },
  {
    id: "hku-foundation",
    name: "HKU Foundation Entrance Scholarship",
    provider: "University of Hong Kong",
    country: "Hong Kong",
    majors: ["Medicine", "Law", "Business", "Engineering", "Architecture"],
    amount: "Up to HKD $191,000/year (full tuition)",
    deadline: "Jan 15, 2027",
    level: "undergraduate",
    fullRide: false,
    tags: ["merit", "high-sat", "international-friendly", "prestigious"],
    summary:
      "HKU's top entrance award for non-local applicants offers a full tuition waiver renewable across the degree for candidates with stellar SAT, AP, or A-Level credentials.",
  },
  {
    id: "schwarzman",
    name: "Schwarzman Scholars",
    provider: "Tsinghua University",
    country: "China",
    majors: ["Business", "Economics", "Political Science", "International Relations", "Law"],
    amount: "Full tuition + stipend + travel",
    deadline: "Sep 17, 2026",
    level: "graduate",
    fullRide: true,
    tags: ["graduate", "leadership", "full-ride", "prestigious", "international-friendly"],
    summary:
      "One-year master's in Global Affairs at Tsinghua's Schwarzman College in Beijing. Fully funded leadership program for ~150 scholars annually.",
  },
  {
    id: "berkeley-regents",
    name: "UC Berkeley Regents' and Chancellor's Scholarship",
    provider: "University of California, Berkeley",
    country: "United States",
    majors: ["Computer Science", "Engineering", "Mathematics", "Physics", "Economics"],
    amount: "Full tuition + $20,000/year stipend",
    deadline: "Jan 15, 2027",
    level: "undergraduate",
    fullRide: true,
    tags: ["merit", "full-ride", "high-sat", "stem", "prestigious"],
    summary:
      "Berkeley's most prestigious merit award recognizes exceptional applicants across all majors with full tuition, fees, and a substantial living stipend for four years on the Berkeley campus.",
  },
  {
    id: "ucla-transfer",
    name: "UCLA Transfer Scholar Award",
    provider: "University of California, Los Angeles",
    country: "United States",
    majors: ["Engineering", "Business", "Computer Science", "Liberal Arts", "Economics"],
    amount: "Up to $15,000/year",
    deadline: "Mar 1, 2027",
    level: "undergraduate",
    fullRide: false,
    tags: ["merit", "international-friendly", "high-sat"],
    summary:
      "UCLA honors exceptional transfer students from California community colleges with renewable merit scholarships recognizing academic excellence and contribution potential.",
  },
  {
    id: "umich-national-merit",
    name: "University of Michigan National Merit Scholarship",
    provider: "University of Michigan",
    country: "United States",
    majors: ["Engineering", "Computer Science", "Mathematics", "Physics", "Liberal Arts"],
    amount: "Full in-state tuition + $5,000/year",
    deadline: "Dec 1, 2026",
    level: "undergraduate",
    fullRide: false,
    tags: ["merit", "high-sat", "stem", "prestigious"],
    summary:
      "Michigan awards top National Merit finalists with full tuition plus a substantial annual scholarship, recognizing extraordinary academic achievement in science and engineering.",
  },
  {
    id: "uva-jefferson",
    name: "Jefferson Scholarship",
    provider: "University of Virginia",
    country: "United States",
    majors: ["Liberal Arts", "Engineering", "Economics", "Mathematics", "Political Science"],
    amount: "Full tuition + room & board + summer stipend",
    deadline: "Jan 10, 2027",
    level: "undergraduate",
    fullRide: true,
    tags: ["merit", "full-ride", "leadership", "prestigious", "high-sat"],
    summary:
      "UVA's flagship merit scholarship for exceptional leaders covers full cost of attendance plus a $6,000 summer enrichment fund for research, internships, and travel.",
  },
  {
    id: "unc-morehead-cain",
    name: "Morehead-Cain Scholarship",
    provider: "University of North Carolina at Chapel Hill",
    country: "United States",
    majors: ["Liberal Arts", "Business", "Political Science", "International Relations", "Economics"],
    amount: "Full cost of attendance + enrichment grants",
    deadline: "Jan 8, 2027",
    level: "undergraduate",
    fullRide: true,
    tags: ["merit", "full-ride", "leadership", "prestigious"],
    summary:
      "UNC's most selective merit award funds exceptional applicants with full tuition, room, board, and travel while providing summer enrichment experiences and mentorship.",
  },
  {
    id: "utaustin-tower",
    name: "UT Austin Forty Acres Scholars",
    provider: "University of Texas at Austin",
    country: "United States",
    majors: ["Engineering", "Computer Science", "Business", "Mathematics", "Physics"],
    amount: "Full cost of attendance + research grants",
    deadline: "Feb 1, 2027",
    level: "undergraduate",
    fullRide: true,
    tags: ["merit", "full-ride", "stem", "research", "leadership"],
    summary:
      "UT Austin's premier scholarship covers full tuition, on-campus housing, and provides funding for research and study abroad experiences for top achievers.",
  },
  {
    id: "williams-finaid",
    name: "Williams College Need-Based Aid",
    provider: "Williams College",
    country: "United States",
    majors: ["Liberal Arts", "Physics", "Mathematics", "Economics", "Environmental Science"],
    amount: "Full cost of attendance",
    deadline: "Jan 5, 2027",
    level: "undergraduate",
    fullRide: true,
    tags: ["need-based", "full-ride", "international-friendly", "prestigious"],
    summary:
      "Williams' need-blind, need-based financial aid covers full tuition, room, board, and travel for admitted students, with no loans in aid packages.",
  },
  {
    id: "pomona-finaid",
    name: "Pomona College International Aid",
    provider: "Pomona College",
    country: "United States",
    majors: ["Liberal Arts", "Computer Science", "Mathematics", "Environmental Science", "Design"],
    amount: "Full demonstrated need (avg ~$60,000/year)",
    deadline: "Jan 3, 2027",
    level: "undergraduate",
    fullRide: false,
    tags: ["need-based", "international-friendly", "prestigious"],
    summary:
      "Pomona meets 100% of demonstrated financial need for admitted international students with grant-only packages — no loans, no work-study expectations.",
  },
  {
    id: "lse-masters-excellence",
    name: "LSE Master's Excellence Scholarship",
    provider: "London School of Economics",
    country: "United Kingdom",
    majors: ["Economics", "Political Science", "International Relations", "Law", "Business"],
    amount: "£25,000–full tuition",
    deadline: "Mar 31, 2027",
    level: "graduate",
    fullRide: false,
    tags: ["merit", "prestigious", "graduate", "international-friendly"],
    summary:
      "LSE's flagship graduate award recognizes exceptional master's candidates with strong academic credentials and potential for global impact.",
  },
  {
    id: "imperial-presidents",
    name: "Imperial College President's Scholarship",
    provider: "Imperial College London",
    country: "United Kingdom",
    majors: ["Engineering", "Computer Science", "Physics", "Mathematics"],
    amount: "Full tuition + £15,000/year stipend",
    deadline: "Jan 15, 2027",
    level: "undergraduate",
    fullRide: true,
    tags: ["merit", "stem", "full-ride", "international-friendly", "prestigious"],
    summary:
      "Imperial's top undergraduate award for exceptional STEM students, combining full fees with a substantial living stipend across the degree.",
  },
  {
    id: "ucl-global-leaders",
    name: "UCL Global Leaders Scholarship",
    provider: "University College London",
    country: "United Kingdom",
    majors: ["Medicine", "Law", "Engineering", "Liberal Arts", "Political Science"],
    amount: "£20,000–£50,000/year",
    deadline: "Feb 28, 2027",
    level: "both",
    fullRide: false,
    tags: ["merit", "leadership", "international-friendly", "prestigious"],
    summary:
      "UCL's transformative award funds high-potential students across all levels, with additional mentorship and networking into London's professional sphere.",
  },
  {
    id: "edinburgh-principal",
    name: "Edinburgh Principal's Career Development Scholarship",
    provider: "University of Edinburgh",
    country: "United Kingdom",
    majors: ["Computer Science", "Engineering", "Economics", "Business", "Environmental Science"],
    amount: "Full tuition",
    deadline: "Feb 1, 2027",
    level: "graduate",
    fullRide: true,
    tags: ["merit", "prestigious", "graduate", "international-friendly", "stem", "full-ride"],
    summary:
      "Edinburgh's most prestigious master's award covers 100% tuition fees for candidates demonstrating exceptional academic excellence and research potential.",
  },
  {
    id: "kcl-law-excellence",
    name: "King's College London Law Excellence Scholarship",
    provider: "King's College London",
    country: "United Kingdom",
    majors: ["Law", "Political Science", "International Relations"],
    amount: "£15,000–full tuition",
    deadline: "Apr 15, 2027",
    level: "graduate",
    fullRide: false,
    tags: ["merit", "prestigious", "international-friendly"],
    summary:
      "KCL Law's elite scholarship recognizes transformational legal minds with demonstrated potential to shape international jurisprudence and governance.",
  },
  {
    id: "manchester-engineering",
    name: "Manchester Engineering Innovation Scholarship",
    provider: "University of Manchester",
    country: "United Kingdom",
    majors: ["Engineering", "Computer Science", "Mathematics", "Physics"],
    amount: "£10,000–£25,000/year",
    deadline: "Mar 15, 2027",
    level: "both",
    fullRide: false,
    tags: ["merit", "stem", "research", "international-friendly"],
    summary:
      "Manchester's flagship STEM award funds ambitious engineers and computer scientists with research interests aligned to industrial innovation.",
  },
  {
    id: "ghent-engineering",
    name: "Ghent University Top-Up Scholarship",
    provider: "Ghent University",
    country: "Belgium",
    majors: ["Engineering", "Computer Science", "Architecture", "Environmental Science"],
    amount: "Full tuition + €1,000/month",
    deadline: "Apr 1, 2027",
    level: "graduate",
    fullRide: true,
    tags: ["merit", "full-ride", "stem", "research", "international-friendly"],
    summary:
      "Ghent's competitive engineering master's award fully funds top applicants with a generous living stipend across two years of cutting-edge research.",
  },
  {
    id: "oslomet-nordic",
    name: "OsloMet International Scholarship",
    provider: "Oslo Metropolitan University",
    country: "Norway",
    majors: ["Business", "Design", "Architecture", "Environmental Science", "Liberal Arts"],
    amount: "Tuition-free + NOK 8,000/month",
    deadline: "Feb 15, 2027",
    level: "both",
    fullRide: true,
    tags: ["merit", "full-ride", "international-friendly", "government"],
    summary:
      "Norway's tuition-free public universities pair with an OsloMet living stipend for exceptional global students bridging Nordic and international learning.",
  },
  {
    id: "iit-delhi-excellence",
    name: "IIT Delhi Excellence Scholarship",
    provider: "Indian Institute of Technology Delhi",
    country: "India",
    majors: ["Computer Science", "Engineering", "Mathematics", "Physics"],
    amount: "Full tuition + ₹200,000 annual stipend",
    deadline: "Mar 15, 2026",
    level: "undergraduate",
    fullRide: true,
    tags: ["merit", "full-ride", "stem", "prestigious"],
    summary:
      "India's premier engineering institute awards merit-based full scholarships to exceptional STEM students, covering tuition and providing substantial living stipends.",
  },
  {
    id: "iim-ahmedabad-fellowship",
    name: "IIM Ahmedabad Need-Based Fellowship",
    provider: "Indian Institute of Management Ahmedabad",
    country: "India",
    majors: ["Business", "Economics", "Law"],
    amount: "Full tuition + internship placement",
    deadline: "May 30, 2026",
    level: "graduate",
    fullRide: true,
    tags: ["need-based", "leadership", "full-ride", "prestigious", "graduate"],
    summary:
      "IIM-A's needs-blind fellowship invests in emerging leaders through complete educational coverage and personalized career mentorship into India's top corporate roles.",
  },
  {
    id: "um-international-excellence",
    name: "Universiti Malaya International Excellence Award",
    provider: "University of Malaya",
    country: "Malaysia",
    majors: ["Computer Science", "Engineering", "Medicine", "Business"],
    amount: "80% tuition + RM 1,500/month",
    deadline: "Apr 20, 2026",
    level: "both",
    fullRide: false,
    tags: ["merit", "international-friendly", "stem", "prestigious"],
    summary:
      "Malaysia's oldest university recognizes exceptional international students with substantial scholarships covering most tuition and living costs in Kuala Lumpur.",
  },
  {
    id: "khazanah-malaysia",
    name: "Khazanah Nasional Scholarship Programme",
    provider: "Khazanah Nasional Berhad",
    country: "Malaysia",
    majors: ["Engineering", "Business", "Economics", "Environmental Science"],
    amount: "Full tuition + living + internship",
    deadline: "Jun 10, 2026",
    level: "undergraduate",
    fullRide: true,
    tags: ["merit", "full-ride", "government", "stem", "leadership"],
    summary:
      "Malaysia's sovereign wealth fund sponsors exceptional graduates with comprehensive packages including full education costs, regional internship placements, and career development.",
  },
  {
    id: "chulalongkorn-royal",
    name: "Chulalongkorn Royal Scholarship",
    provider: "Chulalongkorn University",
    country: "Thailand",
    majors: ["Medicine", "Engineering", "Business", "Law"],
    amount: "Full tuition + ฿15,000/month",
    deadline: "Jul 31, 2026",
    level: "both",
    fullRide: true,
    tags: ["merit", "full-ride", "prestigious", "government"],
    summary:
      "Thailand's most selective institution offers royal-backed scholarships with complete funding and substantial monthly stipends for high-achieving international scholars.",
  },
  {
    id: "ui-asean-merit",
    name: "Universitas Indonesia ASEAN Merit Award",
    provider: "Universitas Indonesia",
    country: "Indonesia",
    majors: ["Computer Science", "Engineering", "Business", "International Relations"],
    amount: "75% tuition + accommodation + research",
    deadline: "May 15, 2026",
    level: "graduate",
    fullRide: false,
    tags: ["merit", "stem", "research", "prestigious", "graduate"],
    summary:
      "Indonesia's flagship university supports ambitious ASEAN scholars pursuing advanced degrees with tuition support, housing, and dedicated research project funding.",
  },
  {
    id: "ateneo-leadership",
    name: "Ateneo Leadership Scholars Program",
    provider: "Ateneo de Manila University",
    country: "Philippines",
    majors: ["Business", "Law", "Political Science", "Liberal Arts"],
    amount: "90% tuition + ₱50,000/year grant",
    deadline: "Apr 30, 2026",
    level: "undergraduate",
    fullRide: false,
    tags: ["merit", "leadership", "prestigious", "need-based"],
    summary:
      "The Philippines' premier Jesuit institution invests in future changemakers through substantial scholarships emphasizing moral leadership and academic excellence.",
  },
  {
    id: "vinuni-fulbright-vietnam",
    name: "VinUniversity Fulbright Vietnam Fellowship",
    provider: "VinUniversity & Fulbright Commission",
    country: "Vietnam",
    majors: ["Business", "Computer Science", "Engineering", "Environmental Science"],
    amount: "Full tuition + living + language training",
    deadline: "Jun 30, 2026",
    level: "both",
    fullRide: true,
    tags: ["merit", "full-ride", "international-friendly", "language-training", "prestigious"],
    summary:
      "Vietnam's premier private university partners with Fulbright to sponsor exceptional students with comprehensive packages including intensive English language preparation and career coaching.",
  },
  {
    id: "nyuad-global",
    name: "NYU Abu Dhabi Global Fellowship",
    provider: "New York University Abu Dhabi",
    country: "United Arab Emirates",
    majors: ["Computer Science", "Engineering", "Business", "Liberal Arts", "Economics"],
    amount: "Full tuition + room & board + $10,000 stipend",
    deadline: "Jan 15, 2027",
    level: "undergraduate",
    fullRide: true,
    tags: ["full-ride", "merit", "international-friendly", "prestigious", "high-sat"],
    summary:
      "Prestigious full-scholarship program covering all expenses for exceptional international students joining NYU's flagship Abu Dhabi campus overlooking the Arabian Gulf.",
  },
  {
    id: "kaust-discovery",
    name: "KAUST Discovery Scholarship",
    provider: "King Abdullah University of Science and Technology",
    country: "Saudi Arabia",
    majors: ["Computer Science", "Engineering", "Mathematics", "Physics", "Environmental Science"],
    amount: "Full tuition + housing + SAR 24,000/year",
    deadline: "Nov 30, 2026",
    level: "graduate",
    fullRide: true,
    tags: ["full-ride", "stem", "research", "merit", "international-friendly", "prestigious"],
    summary:
      "World-class research scholarship for graduate students in STEM, combining full funding with access to cutting-edge facilities on the Red Sea coast.",
  },
  {
    id: "saudi-turki-program",
    name: "Saudi Government Scholarship Program",
    provider: "Saudi Ministry of Education",
    country: "Saudi Arabia",
    majors: ["Medicine", "Engineering", "Computer Science", "Architecture", "Law"],
    amount: "Full tuition + SAR 3,000/month + airfare",
    deadline: "Sep 30, 2026",
    level: "undergraduate",
    fullRide: true,
    tags: ["full-ride", "government", "merit", "stem", "international-friendly"],
    summary:
      "Government-backed scholarship supporting international students in priority fields, combining full financial coverage with structured mentorship and career placement.",
  },
  {
    id: "technion-overseas",
    name: "Technion Overseas Master's Program",
    provider: "Technion - Israel Institute of Technology",
    country: "Israel",
    majors: ["Computer Science", "Engineering", "Mathematics", "Physics"],
    amount: "50% tuition + $8,000 research allowance",
    deadline: "Feb 28, 2027",
    level: "graduate",
    fullRide: false,
    tags: ["merit", "stem", "research", "prestigious", "international-friendly"],
    summary:
      "Competitive scholarship for international master's students in technology and engineering, leveraging Technion's reputation as Israel's top STEM institution.",
  },
  {
    id: "hebrew-global-excellence",
    name: "Hebrew University Global Excellence Scholarship",
    provider: "Hebrew University of Jerusalem",
    country: "Israel",
    majors: ["Law", "Business", "Medicine", "Political Science", "International Relations"],
    amount: "$12,000/year + partial tuition",
    deadline: "Dec 1, 2026",
    level: "graduate",
    fullRide: false,
    tags: ["merit", "prestigious", "leadership", "international-friendly"],
    summary:
      "Recognizes exceptional graduate candidates pursuing advanced degrees in law, medicine, and international studies at Israel's premier research university.",
  },
  {
    id: "hbku-excellence",
    name: "Hamad Bin Khalifa University Excellence Award",
    provider: "Hamad Bin Khalifa University",
    country: "Qatar",
    majors: ["Business", "Engineering", "International Relations", "Law", "Political Science"],
    amount: "Full tuition + QAR 15,000/month",
    deadline: "Oct 15, 2026",
    level: "both",
    fullRide: true,
    tags: ["full-ride", "merit", "leadership", "international-friendly", "prestigious"],
    summary:
      "Comprehensive scholarship recognizing exceptional leadership and academic achievement for both undergraduate and graduate programs in Doha's Education City.",
  },
  {
    id: "bogazici-merit",
    name: "Boğaziçi University International Merit Scholarship",
    provider: "Boğaziçi University",
    country: "Turkey",
    majors: ["Computer Science", "Engineering", "Economics", "Business", "Political Science"],
    amount: "Full tuition + TRY 30,000/year",
    deadline: "Mar 31, 2027",
    level: "undergraduate",
    fullRide: true,
    tags: ["full-ride", "merit", "prestigious", "international-friendly", "language-training"],
    summary:
      "Istanbul's most selective institution offers comprehensive scholarships with Turkish language preparation for outstanding international students entering competitive engineering and business programs.",
  },
  {
    id: "koc-presidential",
    name: "Koç University Presidential Scholarship",
    provider: "Koç University",
    country: "Turkey",
    majors: ["Engineering", "Business", "Computer Science", "Architecture", "Design"],
    amount: "Full tuition + accommodation + $15,000/year",
    deadline: "Apr 15, 2027",
    level: "undergraduate",
    fullRide: true,
    tags: ["full-ride", "merit", "stem", "prestigious", "international-friendly"],
    summary:
      "Koç's flagship scholarship attracts global talent to Istanbul with complete funding, modern campus facilities, and strong industry partnerships.",
  },
  {
    id: "uct-mandela-rhodes",
    name: "Mandela Rhodes Scholarship",
    provider: "Mandela Rhodes Foundation",
    country: "South Africa",
    majors: ["Economics", "Law", "Political Science", "Business", "International Relations"],
    amount: "Full tuition + living + leadership program",
    deadline: "Aug 15, 2026",
    level: "graduate",
    fullRide: true,
    tags: ["merit", "leadership", "full-ride", "prestigious", "international-friendly"],
    summary:
      "Prestigious pan-African award honoring Nelson Mandela's legacy, funding postgraduates pursuing leadership in public service, entrepreneurship, or the professions across the continent.",
  },
  {
    id: "auc-cairo-merit",
    name: "AUC Merit Scholarships",
    provider: "American University in Cairo",
    country: "Egypt",
    majors: ["International Relations", "Business", "Political Science", "Engineering", "Computer Science"],
    amount: "Up to EGP 200,000/year (full tuition)",
    deadline: "Mar 1, 2027",
    level: "undergraduate",
    fullRide: true,
    tags: ["merit", "full-ride", "international-friendly", "prestigious", "leadership"],
    summary:
      "AUC's top merit scholarships for exceptional secondary school graduates across the region, covering full tuition at Cairo's premier English-language liberal arts institution.",
  },
  {
    id: "al-akhawayn-leadership",
    name: "Al Akhawayn African Leadership Award",
    provider: "Al Akhawayn University",
    country: "Morocco",
    majors: ["Business", "Computer Science", "Liberal Arts", "Design", "International Relations"],
    amount: "Full tuition + room & board + exchange",
    deadline: "Apr 30, 2027",
    level: "undergraduate",
    fullRide: true,
    tags: ["merit", "leadership", "full-ride", "international-friendly", "prestigious"],
    summary:
      "Ifrane's most selective award recognizes continental leadership potential, funding African students to study English-language degrees with guaranteed global exchange opportunities.",
  },
  {
    id: "strathmore-presidential",
    name: "Strathmore University Presidential Scholarship",
    provider: "Strathmore University",
    country: "Kenya",
    majors: ["Business", "Economics", "Engineering", "Computer Science", "Law"],
    amount: "Full tuition + accommodation + research grant",
    deadline: "Sep 30, 2026",
    level: "undergraduate",
    fullRide: true,
    tags: ["merit", "stem", "research", "leadership", "full-ride", "prestigious"],
    summary:
      "Strathmore's flagship merit award for top KCSE performers combines full tuition coverage with research funding and mentorship from Kenya's business elite.",
  },
  {
    id: "alu-rwanda-fellows",
    name: "African Leadership University Scholars",
    provider: "African Leadership University",
    country: "Rwanda",
    majors: ["Business", "Computer Science", "Engineering", "Liberal Arts", "International Relations"],
    amount: "Full tuition + living + innovation grant",
    deadline: "Feb 28, 2027",
    level: "undergraduate",
    fullRide: true,
    tags: ["merit", "leadership", "full-ride", "stem", "research", "prestigious"],
    summary:
      "ALU's signature pan-African scholarship funding top performers to study entrepreneurship and technology in Kigali with guaranteed startup incubation funding.",
  },
  {
    id: "mastercard-foundation-scholars",
    name: "Mastercard Foundation Scholars Program",
    provider: "Mastercard Foundation",
    country: "South Africa",
    majors: ["Engineering", "Computer Science", "Medicine", "Business", "Economics"],
    amount: "Full tuition + living + internship",
    deadline: "May 31, 2026",
    level: "undergraduate",
    fullRide: true,
    tags: ["merit", "need-based", "full-ride", "stem", "research", "international-friendly", "leadership"],
    summary:
      "Continental fellowship identifying talented low-income students across Africa, providing university funding plus guaranteed professional internships and mentorship toward economic mobility.",
  },
  {
    id: "usp-engineering-merit",
    name: "USP Engineering Excellence Scholarship",
    provider: "Universidade de São Paulo",
    country: "Brazil",
    majors: ["Engineering", "Computer Science", "Physics"],
    amount: "Full tuition + R$2,500/month",
    deadline: "Aug 31, 2026",
    level: "undergraduate",
    fullRide: false,
    tags: ["merit", "stem", "prestigious"],
    summary:
      "Competitive merit-based award recognizing exceptional academic performance in STEM fields at South America's leading engineering institution.",
  },
  {
    id: "ita-aerospace-fellows",
    name: "ITA Aerospace Research Fellowship",
    provider: "Instituto Tecnológico de Aeronáutica",
    country: "Brazil",
    majors: ["Engineering", "Physics", "Computer Science"],
    amount: "Full tuition + R$3,200/month",
    deadline: "Sep 15, 2026",
    level: "graduate",
    fullRide: true,
    tags: ["merit", "stem", "research", "prestigious", "full-ride"],
    summary:
      "Prestigious fellowship for graduate students pursuing aerospace engineering research with international collaboration opportunities.",
  },
  {
    id: "tec-monterrey-leaders",
    name: "Tec de Monterrey Global Leaders Program",
    provider: "Tecnológico de Monterrey",
    country: "Mexico",
    majors: ["Business", "Engineering", "Economics", "International Relations"],
    amount: "75% tuition + exchange program",
    deadline: "Mar 30, 2027",
    level: "undergraduate",
    fullRide: false,
    tags: ["merit", "leadership", "international-friendly"],
    summary:
      "Transformative scholarship for high-potential students combining rigorous academics with international mobility and leadership development.",
  },
  {
    id: "unam-conacyt",
    name: "UNAM National Science Scholarship",
    provider: "Universidad Nacional Autónoma de México",
    country: "Mexico",
    majors: ["Physics", "Mathematics", "Biology", "Computer Science"],
    amount: "Full tuition + MXN 20,000/month",
    deadline: "Jul 20, 2026",
    level: "graduate",
    fullRide: true,
    tags: ["merit", "stem", "research", "government", "full-ride"],
    summary:
      "Government-backed award supporting cutting-edge scientific research across Mexico's most prestigious research university.",
  },
  {
    id: "uca-engineering",
    name: "UCA Engineering Excellence Award",
    provider: "Pontificia Universidad Católica Argentina",
    country: "Argentina",
    majors: ["Engineering", "Architecture", "Computer Science"],
    amount: "80% tuition + ARS 45,000/month",
    deadline: "Oct 15, 2026",
    level: "undergraduate",
    fullRide: false,
    tags: ["merit", "stem", "prestigious"],
    summary:
      "Selective award honoring engineering excellence and innovation at Argentina's leading Catholic research institution.",
  },
  {
    id: "uchile-doctoral",
    name: "University of Chile Doctoral Innovation Fellowship",
    provider: "Universidad de Chile",
    country: "Chile",
    majors: ["Engineering", "Physics", "Computer Science", "Environmental Science"],
    amount: "CLP 3,500,000/year",
    deadline: "Feb 28, 2027",
    level: "graduate",
    fullRide: true,
    tags: ["merit", "research", "stem", "government", "full-ride"],
    summary:
      "Flagship doctoral fellowship driving scientific innovation and technological advancement across Chile's national university.",
  },
  {
    id: "uandes-business",
    name: "Universidad de los Andes Business Leadership Scholarship",
    provider: "Universidad de los Andes",
    country: "Colombia",
    majors: ["Business", "Economics", "International Relations"],
    amount: "90% tuition + mentorship program",
    deadline: "Sep 30, 2026",
    level: "undergraduate",
    fullRide: false,
    tags: ["merit", "leadership", "international-friendly", "prestigious"],
    summary:
      "Elite scholarship developing future business leaders with access to top faculty and exclusive networking with Colombia's corporate elite.",
  },
  {
    id: "puc-chile-stem",
    name: "PUC Chile STEM Research Grant",
    provider: "Pontificia Universidad Católica de Chile",
    country: "Chile",
    majors: ["Computer Science", "Engineering", "Biology", "Physics"],
    amount: "Full tuition + UF 400/month research budget",
    deadline: "Jan 31, 2027",
    level: "graduate",
    fullRide: true,
    tags: ["merit", "stem", "research", "prestigious", "full-ride"],
    summary:
      "Prestigious research fellowship connecting emerging scientists with Chile's premier Catholic research ecosystem and international collaborators.",
  },
  {
    id: "vanderbilt-cornelius",
    name: "Cornelius Vanderbilt Scholarship",
    provider: "Vanderbilt University",
    country: "United States",
    majors: ["Economics", "Business", "Engineering", "Computer Science", "Mathematics"],
    amount: "Full tuition + room & board + summer stipend",
    deadline: "Jan 15, 2027",
    level: "undergraduate",
    fullRide: true,
    tags: ["merit", "full-ride", "high-sat", "prestigious", "leadership"],
    summary:
      "Vanderbilt's premier merit scholarship for exceptional scholars, covering all costs plus a summer enrichment stipend for research and internships. Winners join an elite leadership cohort.",
  },
  {
    id: "emory-scholars",
    name: "Emory Scholars Program",
    provider: "Emory University",
    country: "United States",
    majors: ["Business", "Economics", "Political Science", "International Relations", "Liberal Arts"],
    amount: "Full tuition + room & board",
    deadline: "Jan 10, 2027",
    level: "undergraduate",
    fullRide: true,
    tags: ["merit", "full-ride", "leadership", "prestigious"],
    summary:
      "Emory's competitive merit scholarship recognizing intellectual merit and leadership potential, fully covering undergraduate costs at this renowned Atlanta institution.",
  },
  {
    id: "rice-trustee-distinguished",
    name: "Trustee Distinguished Scholar Award",
    provider: "Rice University",
    country: "United States",
    majors: ["Engineering", "Computer Science", "Mathematics", "Physics", "Business"],
    amount: "Full tuition, room, board & fees",
    deadline: "Jan 5, 2027",
    level: "undergraduate",
    fullRide: true,
    tags: ["merit", "full-ride", "high-sat", "stem", "prestigious"],
    summary:
      "Rice's highest merit award for intellectually exceptional students, providing complete undergraduate funding at Houston's leading STEM-focused institution.",
  },
  {
    id: "bu-trustee",
    name: "Boston University Trustee Scholarship",
    provider: "Boston University",
    country: "United States",
    majors: ["Engineering", "Business", "Computer Science", "Economics", "Liberal Arts"],
    amount: "Full tuition",
    deadline: "Jan 15, 2027",
    level: "undergraduate",
    fullRide: false,
    tags: ["merit", "high-sat", "prestigious"],
    summary:
      "Boston University's elite merit award recognizing academic excellence, covering full tuition for stellar applicants. Trustee Scholars gain priority course registration and exclusive networking.",
  },
  {
    id: "tufts-presidential",
    name: "Tufts Presidential Scholarship",
    provider: "Tufts University",
    country: "United States",
    majors: ["International Relations", "Engineering", "Computer Science", "Mathematics", "Liberal Arts"],
    amount: "Up to $25,000/year",
    deadline: "Jan 10, 2027",
    level: "undergraduate",
    fullRide: false,
    tags: ["merit", "high-sat", "international-friendly"],
    summary:
      "Tufts recognizes exceptional global citizens through this merit scholarship, emphasizing international perspectives and rigorous academics.",
  },
  {
    id: "gatech-stamps",
    name: "Stamps President's Scholars Program",
    provider: "Georgia Institute of Technology",
    country: "United States",
    majors: ["Engineering", "Computer Science", "Mathematics", "Physics", "Architecture"],
    amount: "Full cost of attendance + enrichment",
    deadline: "Dec 15, 2026",
    level: "undergraduate",
    fullRide: true,
    tags: ["merit", "full-ride", "stem", "leadership", "prestigious"],
    summary:
      "Georgia Tech's prestigious STEM-focused scholarship through the Stamps Family, fully funding exceptional engineering and technology students with industry mentorship.",
  },
  {
    id: "cmu-presidential",
    name: "Carnegie Mellon Presidential Scholarship",
    provider: "Carnegie Mellon University",
    country: "United States",
    majors: ["Computer Science", "Engineering", "Business", "Mathematics", "Architecture"],
    amount: "Up to full tuition",
    deadline: "Jan 15, 2027",
    level: "undergraduate",
    fullRide: false,
    tags: ["merit", "high-sat", "stem", "prestigious"],
    summary:
      "Carnegie Mellon's premier merit scholarship for exceptional technologists and innovators with access to cutting-edge labs in Pittsburgh's powerhouse institution.",
  },
  {
    id: "uw-merit",
    name: "Foster School Merit Award",
    provider: "University of Washington",
    country: "United States",
    majors: ["Business", "Economics", "Computer Science", "Engineering"],
    amount: "Up to $20,000/year",
    deadline: "Dec 1, 2026",
    level: "undergraduate",
    fullRide: false,
    tags: ["merit", "stem"],
    summary:
      "University of Washington's competitive merit scholarship recognizing academic and leadership excellence, particularly valuable for students pursuing STEM and business fields.",
  },
  {
    id: "msu-alumni-distinction",
    name: "Michigan State Alumni Distinction Award",
    provider: "Michigan State University",
    country: "United States",
    majors: ["Engineering", "Environmental Science", "Business", "Computer Science", "Biology"],
    amount: "$15,000–$25,000/year",
    deadline: "Feb 28, 2027",
    level: "undergraduate",
    fullRide: false,
    tags: ["merit", "stem", "leadership"],
    summary:
      "MSU's merit-based award honoring strong academics and extracurricular achievement, particularly supporting first-generation and underrepresented students in engineering and environmental science.",
  },
  {
    id: "wesleyan-freeman",
    name: "Freeman Asian Scholarship",
    provider: "Wesleyan University",
    country: "United States",
    majors: ["Liberal Arts", "Economics", "Mathematics", "Physics", "Political Science"],
    amount: "Full tuition for four years",
    deadline: "Jan 5, 2027",
    level: "undergraduate",
    fullRide: true,
    tags: ["merit", "full-ride", "high-sat", "international-friendly", "prestigious"],
    summary:
      "Wesleyan's prestigious scholarship for exceptional students from East/Southeast Asia, covering full tuition over four years at the renowned liberal arts campus.",
  },
  {
    id: "sciences-po-boutmy",
    name: "Sciences Po Émile Boutmy Scholarship",
    provider: "Sciences Po",
    country: "France",
    majors: ["Political Science", "International Relations", "Economics", "Law"],
    amount: "Up to €15,300/year tuition",
    deadline: "Jan 15, 2027",
    level: "undergraduate",
    fullRide: false,
    tags: ["merit", "prestigious", "international-friendly"],
    summary:
      "Sciences Po's flagship award for exceptional non-EU undergraduates, covering tuition for talented candidates demonstrating academic excellence and leadership in social sciences.",
  },
  {
    id: "bocconi-merit-undergrad",
    name: "Bocconi Merit-Based Award",
    provider: "Bocconi University",
    country: "Italy",
    majors: ["Business", "Economics"],
    amount: "Up to €30,000/year",
    deadline: "Feb 28, 2027",
    level: "undergraduate",
    fullRide: false,
    tags: ["merit", "prestigious", "leadership"],
    summary:
      "Competitive scholarship covering tuition for high-achieving undergraduates in business and economics with demonstrated leadership and international outlook.",
  },
  {
    id: "uva-amsterdam-excellence",
    name: "University of Amsterdam Excellence Scholarship",
    provider: "University of Amsterdam",
    country: "Netherlands",
    majors: ["Computer Science", "Engineering", "Mathematics", "Physics"],
    amount: "€25,000/year",
    deadline: "Mar 15, 2027",
    level: "undergraduate",
    fullRide: false,
    tags: ["merit", "stem", "international-friendly"],
    summary:
      "Merit-based award supporting exceptional STEM undergraduates from across the globe pursuing rigorous programs in Amsterdam's world-class facilities.",
  },
  {
    id: "leiden-excellence-bachelor",
    name: "Leiden University Excellence Scholarship",
    provider: "Leiden University",
    country: "Netherlands",
    majors: ["Law", "International Relations", "Medicine", "Liberal Arts"],
    amount: "€10,000–€25,000/year",
    deadline: "Dec 1, 2026",
    level: "undergraduate",
    fullRide: false,
    tags: ["merit", "prestigious", "international-friendly"],
    summary:
      "Prestigious scholarship for outstanding international undergraduates across diverse disciplines, partially covering tuition at the Netherlands' oldest university.",
  },
  {
    id: "maastricht-high-potential",
    name: "Maastricht University High Potential Scholarship",
    provider: "Maastricht University",
    country: "Netherlands",
    majors: ["Business", "Engineering", "Political Science", "Environmental Science"],
    amount: "Full tuition + €11,400/year living",
    deadline: "Apr 30, 2027",
    level: "undergraduate",
    fullRide: true,
    tags: ["merit", "leadership", "international-friendly", "full-ride"],
    summary:
      "Targeted support for high-potential undergraduates demonstrating academic excellence, leadership qualities, and commitment to social responsibility in Maastricht's PBL programs.",
  },
  {
    id: "epfl-bachelor-excellence",
    name: "EPFL Excellence Bachelor Scholarship",
    provider: "École polytechnique fédérale de Lausanne",
    country: "Switzerland",
    majors: ["Computer Science", "Engineering", "Physics", "Mathematics"],
    amount: "CHF 16,000/year",
    deadline: "Jan 31, 2027",
    level: "undergraduate",
    fullRide: false,
    tags: ["stem", "merit", "prestigious", "international-friendly"],
    summary:
      "Competitive scholarship for exceptional STEM undergraduates entering one of Europe's top engineering and technology institutions in Lausanne.",
  },
  {
    id: "ku-leuven-bachelor",
    name: "KU Leuven Global Scholars Programme",
    provider: "KU Leuven",
    country: "Belgium",
    majors: ["Engineering", "Computer Science", "Law", "Business"],
    amount: "Up to €25,000/year",
    deadline: "Feb 15, 2027",
    level: "undergraduate",
    fullRide: false,
    tags: ["merit", "international-friendly", "stem"],
    summary:
      "International scholarship program recognizing outstanding undergraduate potential across engineering, technology, and professional disciplines at Belgium's premier university.",
  },
  {
    id: "trinity-foundation",
    name: "Trinity College Dublin Foundation Scholarship",
    provider: "Trinity College Dublin",
    country: "Ireland",
    majors: ["Computer Science", "Engineering", "Liberal Arts", "Mathematics"],
    amount: "Free tuition + meals + accommodation",
    deadline: "Mar 1, 2027",
    level: "undergraduate",
    fullRide: true,
    tags: ["merit", "stem", "prestigious", "full-ride"],
    summary:
      "Foundation scholarship — Ireland's most prestigious undergraduate award — supporting exceptional Trinity students with free tuition, accommodation, meals, and lifelong privileges.",
  },
  {
    id: "durham-scholars",
    name: "Durham University Scholars Programme",
    provider: "Durham University",
    country: "United Kingdom",
    majors: ["Law", "Political Science", "Economics", "Physics"],
    amount: "£5,000–£10,000/year",
    deadline: "Jan 20, 2027",
    level: "undergraduate",
    fullRide: false,
    tags: ["merit", "prestigious"],
    summary:
      "Selective scholarship recognizing exceptional academic talent and potential for leadership among UK and international undergraduates at this Russell Group institution.",
  },
  {
    id: "st-andrews-excellence",
    name: "St Andrews Wallace Award",
    provider: "University of St Andrews",
    country: "United Kingdom",
    majors: ["Computer Science", "Liberal Arts", "International Relations", "Physics"],
    amount: "£5,000/year",
    deadline: "Feb 28, 2027",
    level: "undergraduate",
    fullRide: false,
    tags: ["merit", "prestigious", "international-friendly"],
    summary:
      "Wallace scholarship supporting exceptional international and domestic undergraduates pursuing innovative academic pathways at Scotland's ancient university.",
  },
  {
    id: "tsinghua-undergrad-merit",
    name: "Tsinghua Undergraduate Merit Scholarship",
    provider: "Tsinghua University",
    country: "China",
    majors: ["Engineering", "Computer Science", "Economics", "Business"],
    amount: "Up to ¥40,000/year + accommodation",
    deadline: "Jan 15, 2027",
    level: "undergraduate",
    fullRide: false,
    tags: ["merit", "stem", "prestigious", "international-friendly"],
    summary:
      "Recognizes exceptional undergraduate talent in engineering and technology at Tsinghua's flagship programs. Awarded to top-performing international students demonstrating leadership.",
  },
  {
    id: "peking-yenching-undergrad",
    name: "Peking University Yenching Scholarship",
    provider: "Peking University",
    country: "China",
    majors: ["International Relations", "Political Science", "Liberal Arts", "Economics"],
    amount: "Full tuition + ¥80,000/year living",
    deadline: "Mar 1, 2027",
    level: "undergraduate",
    fullRide: true,
    tags: ["full-ride", "prestigious", "international-friendly", "leadership"],
    summary:
      "Prestigious full scholarship for global scholars studying international relations and liberal arts at Peking's historic campus, emphasizing cross-cultural engagement and academic excellence.",
  },
  {
    id: "yonsei-underwood",
    name: "Yonsei Underwood International Scholarship",
    provider: "Yonsei University",
    country: "South Korea",
    majors: ["Business", "Engineering", "International Relations", "Economics"],
    amount: "30–100% tuition + housing",
    deadline: "Feb 28, 2027",
    level: "undergraduate",
    fullRide: false,
    tags: ["merit", "international-friendly", "prestigious", "leadership"],
    summary:
      "Competitive scholarship for exceptional undergraduates in Yonsei's Underwood International College with focus on global leadership and English-medium instruction.",
  },
  {
    id: "korea-univ-global-ku",
    name: "Global KU Merit Scholarship",
    provider: "Korea University",
    country: "South Korea",
    majors: ["Computer Science", "Engineering", "Business", "International Relations"],
    amount: "50–100% tuition coverage",
    deadline: "Apr 15, 2027",
    level: "undergraduate",
    fullRide: true,
    tags: ["merit", "stem", "prestigious", "international-friendly", "full-ride"],
    summary:
      "Merit-based full or partial scholarship for outstanding undergraduates pursuing engineering and business studies at one of Korea's top three private universities.",
  },
  {
    id: "skku-excellence",
    name: "Sungkyunkwan Excellence Undergraduate Award",
    provider: "Sungkyunkwan University",
    country: "South Korea",
    majors: ["Engineering", "Computer Science", "Business", "Medicine"],
    amount: "$15,000/year",
    deadline: "May 1, 2027",
    level: "undergraduate",
    fullRide: false,
    tags: ["merit", "stem", "prestigious", "research"],
    summary:
      "Honors undergraduate scholars excelling in STEM fields at Korea's oldest university, with access to cutting-edge research facilities and mentorship from leading academics.",
  },
  {
    id: "nus-global-merit",
    name: "NUS Global Merit Scholarship",
    provider: "National University of Singapore",
    country: "Singapore",
    majors: ["Computer Science", "Engineering", "Business", "Economics"],
    amount: "Full tuition + S$6,000/year + accommodation",
    deadline: "Jan 31, 2027",
    level: "undergraduate",
    fullRide: true,
    tags: ["full-ride", "merit", "stem", "prestigious", "international-friendly"],
    summary:
      "Premier full scholarship for world-class undergraduate talent across engineering and computing disciplines, positioning scholars in Singapore's vibrant innovation ecosystem.",
  },
  {
    id: "hkust-reaching-out",
    name: "HKUST Reaching Out Award",
    provider: "Hong Kong University of Science and Technology",
    country: "Hong Kong",
    majors: ["Engineering", "Computer Science", "Physics", "Mathematics"],
    amount: "HKD $80,000/year",
    deadline: "Mar 15, 2027",
    level: "undergraduate",
    fullRide: false,
    tags: ["merit", "stem", "prestigious", "research"],
    summary:
      "Competitive scholarship for scientifically brilliant undergraduates in HKUST's renowned engineering and science programs, emphasizing research engagement and innovation.",
  },
  {
    id: "ntu-taiwan-sigma",
    name: "NTU College Sigma Fellowship",
    provider: "National Taiwan University",
    country: "Taiwan",
    majors: ["Engineering", "Computer Science", "Business", "Architecture"],
    amount: "TWD 250,000/year + research support",
    deadline: "Feb 10, 2027",
    level: "undergraduate",
    fullRide: false,
    tags: ["merit", "stem", "research", "prestigious"],
    summary:
      "Selective scholarship for high-achieving undergraduates pursuing innovation-driven studies, with mentorship, research funding, and entrepreneurship development.",
  },
  {
    id: "auckland-international-merit",
    name: "University of Auckland International Excellence",
    provider: "University of Auckland",
    country: "New Zealand",
    majors: ["Engineering", "Business", "Computer Science", "Medicine"],
    amount: "NZD $25,000/year",
    deadline: "Nov 30, 2026",
    level: "undergraduate",
    fullRide: false,
    tags: ["merit", "stem", "prestigious", "international-friendly"],
    summary:
      "Prestigious award recognizing international undergraduate excellence at New Zealand's leading university, supporting students pursuing engineering and professional studies.",
  },
  {
    id: "ncku-excellence",
    name: "NCKU Excellence Undergraduate Award",
    provider: "National Cheng Kung University",
    country: "Taiwan",
    majors: ["Engineering", "Computer Science", "Physics", "Environmental Science"],
    amount: "Full tuition + living allowance",
    deadline: "Apr 30, 2027",
    level: "undergraduate",
    fullRide: true,
    tags: ["full-ride", "merit", "stem", "prestigious"],
    summary:
      "Comprehensive full scholarship for exceptional undergraduates in Taiwan's premier engineering institution, with research opportunities and international exchange programs.",
  },
  {
    id: "davis-uwc-scholars",
    name: "Davis United World College Scholars",
    provider: "Davis UWC Scholars Program",
    country: "United States",
    majors: ["Political Science", "International Relations", "Economics", "Business", "Liberal Arts"],
    amount: "$20,000–$30,000 over 4 years",
    deadline: "Nov 15, 2026",
    level: "undergraduate",
    fullRide: false,
    tags: ["merit", "international-friendly", "leadership", "prestigious"],
    summary:
      "Prestigious need-based scholarship for UWC graduates entering nearly 100 partner US universities, recognizing global engagement and ethical leadership across four years of undergraduate study.",
  },
  {
    id: "questbridge-match",
    name: "QuestBridge National College Match",
    provider: "QuestBridge",
    country: "United States",
    majors: ["Computer Science", "Engineering", "Business", "Economics", "Law"],
    amount: "Full 4-year scholarship (~$300,000)",
    deadline: "Sep 28, 2026",
    level: "undergraduate",
    fullRide: true,
    tags: ["need-based", "full-ride", "merit", "high-sat", "prestigious"],
    summary:
      "Full-ride match program connecting extraordinary low-income students with 50+ leading US universities through binding-decision matching, removing barriers from application to graduation.",
  },
  {
    id: "aga-khan-foundation",
    name: "Aga Khan Foundation International Scholarship",
    provider: "Aga Khan Foundation",
    country: "United Kingdom",
    majors: ["Medicine", "Business", "Engineering", "International Relations", "Architecture"],
    amount: "Up to £30,000/year (50% loan / 50% grant)",
    deadline: "Feb 28, 2027",
    level: "undergraduate",
    fullRide: false,
    tags: ["need-based", "merit", "international-friendly", "leadership"],
    summary:
      "Merit and need-based scholarships for exceptional students from select developing countries pursuing undergraduate studies abroad, emphasizing service to community.",
  },
  {
    id: "diana-award-bursary",
    name: "Diana Award Bursary Scheme",
    provider: "The Diana Award",
    country: "United Kingdom",
    majors: ["Law", "Political Science", "International Relations", "Liberal Arts"],
    amount: "£5,000–£15,000/year",
    deadline: "Apr 30, 2027",
    level: "undergraduate",
    fullRide: false,
    tags: ["merit", "leadership", "international-friendly"],
    summary:
      "Bursary supporting young leaders studying humanities and social sciences at UK universities, prioritizing those making meaningful impact in their communities.",
  },
  {
    id: "ofid-international",
    name: "OFID Scholarship Award",
    provider: "OPEC Fund for International Development",
    country: "Austria",
    majors: ["Engineering", "Computer Science", "Business", "Economics", "Environmental Science"],
    amount: "$15,000–$35,000/year",
    deadline: "Jun 30, 2026",
    level: "undergraduate",
    fullRide: false,
    tags: ["need-based", "international-friendly", "merit", "stem"],
    summary:
      "Development-focused scholarship supporting undergraduate studies in STEM and business for talented students from OPEC member countries and developing nations.",
  },
  {
    id: "open-society-undergrad",
    name: "Open Society Undergraduate Fellowship",
    provider: "Open Society Foundations",
    country: "United States",
    majors: ["Political Science", "Law", "International Relations", "Economics", "Liberal Arts"],
    amount: "Up to $25,000/year",
    deadline: "Nov 1, 2026",
    level: "undergraduate",
    fullRide: false,
    tags: ["merit", "international-friendly", "leadership", "prestigious"],
    summary:
      "Competitive fellowship for intellectually ambitious undergraduates from post-Soviet states and emerging democracies pursuing studies in humanities and social sciences at US institutions.",
  },
  {
    id: "rotary-global-undergrad",
    name: "Rotary Global Undergraduate Exchange",
    provider: "Rotary International",
    country: "Canada",
    majors: ["International Relations", "Business", "Engineering", "Political Science", "Environmental Science"],
    amount: "Up to CAD $30,000/year",
    deadline: "Mar 15, 2027",
    level: "undergraduate",
    fullRide: false,
    tags: ["merit", "international-friendly", "leadership", "prestigious"],
    summary:
      "Multi-year scholarship enabling global citizens to pursue undergraduate education in Canada while advancing peace and cross-cultural understanding through Rotary's local clubs.",
  },
];
