export type Scholarship = {
  id: string;
  name: string;
  provider: string;
  country: string;
  majors: string[];
  amount: string;
  deadline: string;
  level: "undergraduate" | "graduate" | "both";
  fullRide: boolean;
  tags: string[];
  summary: string;
};

export const COUNTRIES = [
  "United States",
  "United Kingdom",
  "Canada",
  "Germany",
  "Australia",
  "Japan",
  "South Korea",
  "Netherlands",
  "Singapore",
  "Switzerland",
  "France",
  "Sweden",
  "Denmark",
  "Italy",
  "Spain",
  "Ireland",
  "Hong Kong",
  "China",
];

export const MAJORS = [
  "Computer Science",
  "Engineering",
  "Business",
  "Economics",
  "Mathematics",
  "Physics",
  "Biology",
  "Medicine",
  "Law",
  "Political Science",
  "International Relations",
  "Liberal Arts",
  "Architecture",
  "Design",
  "Environmental Science",
];

export const SCHOLARSHIPS: Scholarship[] = [
  {
    id: "harvard-finaid",
    name: "Harvard Financial Aid Initiative",
    provider: "Harvard University",
    country: "United States",
    majors: ["Computer Science", "Economics", "Liberal Arts", "Mathematics", "Physics", "Biology"],
    amount: "Full tuition + room & board",
    deadline: "Jan 1, 2027",
    level: "undergraduate",
    fullRide: true,
    tags: ["need-based", "ivy", "full-ride", "high-sat", "international-friendly"],
    summary:
      "Need-based grant covering 100% of demonstrated financial need for admitted students from any country. Families earning under $85K pay nothing.",
  },
  {
    id: "mit-need",
    name: "MIT Need-Based Aid",
    provider: "Massachusetts Institute of Technology",
    country: "United States",
    majors: ["Computer Science", "Engineering", "Mathematics", "Physics"],
    amount: "Up to $80,000 / year",
    deadline: "Feb 15, 2027",
    level: "undergraduate",
    fullRide: true,
    tags: ["need-based", "stem", "research", "high-sat", "international-friendly"],
    summary:
      "MIT meets 100% of demonstrated need with grants — no loans. Open to students worldwide pursuing STEM-focused degrees.",
  },
  {
    id: "stanford-knight-hennessy",
    name: "Knight-Hennessy Scholars",
    provider: "Stanford University",
    country: "United States",
    majors: ["Business", "Engineering", "Law", "Medicine", "Computer Science", "Economics"],
    amount: "Full graduate tuition + stipend",
    deadline: "Oct 11, 2026",
    level: "graduate",
    fullRide: true,
    tags: ["leadership", "graduate", "full-ride", "merit", "international-friendly"],
    summary:
      "Up to three years of full funding for graduate study at Stanford with a leadership development program. 100 scholars per year.",
  },
  {
    id: "yale-finaid",
    name: "Yale International Aid",
    provider: "Yale University",
    country: "United States",
    majors: ["Liberal Arts", "Political Science", "Economics", "International Relations", "Law"],
    amount: "Full demonstrated need",
    deadline: "Jan 2, 2027",
    level: "undergraduate",
    fullRide: true,
    tags: ["need-based", "ivy", "international-friendly", "full-ride"],
    summary:
      "Yale is need-blind for all applicants including international students. Average aid award: $66,000/year.",
  },
  {
    id: "princeton-finaid",
    name: "Princeton Aid for International Students",
    provider: "Princeton University",
    country: "United States",
    majors: ["Mathematics", "Physics", "Economics", "Computer Science", "Liberal Arts", "Engineering"],
    amount: "Full need + no loans",
    deadline: "Jan 1, 2027",
    level: "undergraduate",
    fullRide: true,
    tags: ["need-based", "ivy", "full-ride", "international-friendly"],
    summary:
      "Princeton replaced loans with grants. Aid covers full demonstrated need including travel, books, and personal expenses.",
  },
  {
    id: "columbia-finaid",
    name: "Columbia Need-Based Aid",
    provider: "Columbia University",
    country: "United States",
    majors: ["Business", "Engineering", "International Relations", "Liberal Arts", "Law"],
    amount: "Up to full tuition",
    deadline: "Jan 1, 2027",
    level: "undergraduate",
    fullRide: true,
    tags: ["need-based", "ivy", "international-friendly", "high-sat"],
    summary:
      "Need-blind admission for all applicants. 100% of need met with grants and work-study; no loans required.",
  },
  {
    id: "fulbright",
    name: "Fulbright Foreign Student Program",
    provider: "U.S. Department of State",
    country: "United States",
    majors: ["International Relations", "Political Science", "Economics", "Liberal Arts", "Engineering", "Medicine"],
    amount: "Tuition + living + travel",
    deadline: "May 15, 2027",
    level: "graduate",
    fullRide: true,
    tags: ["government", "graduate", "leadership", "international-friendly"],
    summary:
      "Prestigious U.S. government scholarship for graduate study. Covers tuition, books, airfare, health insurance, and a living stipend.",
  },
  {
    id: "brown-finaid",
    name: "Brown University Need-Based Financial Aid",
    provider: "Brown University",
    country: "United States",
    majors: ["Computer Science", "Engineering", "Liberal Arts", "Economics", "International Relations"],
    amount: "Full demonstrated need (up to ~$90,000/year)",
    deadline: "Jan 3, 2027",
    level: "undergraduate",
    fullRide: false,
    tags: ["need-based", "ivy", "international-friendly", "prestigious"],
    summary:
      "Brown meets 100% of demonstrated financial need for admitted international undergraduates through its need-blind aid program, with no loans in aid packages for families below set income thresholds.",
  },
  {
    id: "upenn-finaid",
    name: "Penn International Student Financial Aid",
    provider: "University of Pennsylvania",
    country: "United States",
    majors: ["Business", "Economics", "Engineering", "Computer Science", "Liberal Arts"],
    amount: "Full demonstrated need (avg ~$65,000/year)",
    deadline: "Jan 5, 2027",
    level: "undergraduate",
    fullRide: false,
    tags: ["need-based", "ivy", "international-friendly", "prestigious"],
    summary:
      "Penn admits international undergraduates need-blind and meets 100% of demonstrated need with grant-based aid, replacing loans with scholarship funds for all qualifying students.",
  },
  {
    id: "cornell-tata",
    name: "Tata Scholarship for Students from India",
    provider: "Cornell University",
    country: "United States",
    majors: ["Engineering", "Computer Science", "Business", "Economics", "Architecture"],
    amount: "Up to full tuition and fees (~$70,000/year)",
    deadline: "Jan 2, 2027",
    level: "undergraduate",
    fullRide: false,
    tags: ["need-based", "ivy", "international-friendly", "prestigious", "high-sat"],
    summary:
      "Endowed by the Tata Education and Development Trust, this fund supports up to 20 Indian undergraduates at Cornell each year with substantial need-based aid covering tuition, room, and board.",
  },
  {
    id: "dartmouth-finaid",
    name: "Dartmouth International Need-Based Aid",
    provider: "Dartmouth College",
    country: "United States",
    majors: ["Liberal Arts", "Economics", "Engineering", "Political Science", "Environmental Science"],
    amount: "Full demonstrated need (up to ~$87,000/year)",
    deadline: "Jan 3, 2027",
    level: "undergraduate",
    fullRide: false,
    tags: ["need-based", "ivy", "international-friendly", "prestigious"],
    summary:
      "Dartmouth is one of a handful of U.S. colleges that is need-blind for international applicants and meets 100% of demonstrated need with no-loan aid packages funded by its endowment.",
  },
  {
    id: "uchicago-odyssey",
    name: "Odyssey Scholarship",
    provider: "University of Chicago",
    country: "United States",
    majors: ["Economics", "Mathematics", "Physics", "Computer Science", "Liberal Arts"],
    amount: "Full tuition + summer stipend",
    deadline: "Jan 5, 2027",
    level: "undergraduate",
    fullRide: true,
    tags: ["need-based", "full-ride", "international-friendly", "prestigious", "high-sat"],
    summary:
      "UChicago's Odyssey program eliminates loans and guarantees free tuition for admitted students from middle- and lower-income families, including international applicants, plus paid summer internships.",
  },
  {
    id: "duke-karsh",
    name: "Karsh International Scholars Program",
    provider: "Duke University",
    country: "United States",
    majors: ["Engineering", "Computer Science", "Economics", "Political Science", "International Relations"],
    amount: "Full need + research and travel stipends",
    deadline: "Jan 3, 2027",
    level: "undergraduate",
    fullRide: true,
    tags: ["need-based", "merit", "full-ride", "international-friendly", "research", "prestigious", "high-sat"],
    summary:
      "Duke's flagship Karsh program selects exceptional international undergraduates for full need-based aid plus dedicated funding for summer research, conferences, and global experiences across all four years.",
  },
  {
    id: "northwestern-finaid",
    name: "Northwestern International Financial Aid",
    provider: "Northwestern University",
    country: "United States",
    majors: ["Engineering", "Business", "Economics", "Computer Science", "Liberal Arts"],
    amount: "Full demonstrated need (up to ~$85,000/year)",
    deadline: "Jan 2, 2027",
    level: "undergraduate",
    fullRide: false,
    tags: ["need-based", "international-friendly", "prestigious"],
    summary:
      "Northwestern admits international students need-aware but commits to meeting 100% of demonstrated financial need for all admitted international undergraduates with no-loan aid packages.",
  },
  {
    id: "caltech-finaid",
    name: "Caltech Need-Based Scholarships",
    provider: "California Institute of Technology",
    country: "United States",
    majors: ["Physics", "Mathematics", "Computer Science", "Engineering", "Biology"],
    amount: "Full demonstrated need (avg ~$55,000/year)",
    deadline: "Jan 3, 2027",
    level: "undergraduate",
    fullRide: false,
    tags: ["need-based", "stem", "international-friendly", "research", "prestigious", "high-sat"],
    summary:
      "Caltech meets 100% of demonstrated need for international undergraduates admitted to its rigorous STEM programs, with aid packages built primarily from institutional grants rather than loans.",
  },
  {
    id: "jhu-hodson",
    name: "Hodson Trust Scholarship",
    provider: "Johns Hopkins University",
    country: "United States",
    majors: ["Biology", "Medicine", "Engineering", "Computer Science", "Physics"],
    amount: "Up to $40,000/year",
    deadline: "Jan 2, 2027",
    level: "undergraduate",
    fullRide: false,
    tags: ["merit", "stem", "international-friendly", "research", "prestigious", "high-sat"],
    summary:
      "Johns Hopkins awards the prestigious Hodson Trust Scholarship to a small cohort of incoming undergraduates, including internationals, based on outstanding academic achievement and leadership potential.",
  },
  {
    id: "nyu-anbryce",
    name: "AnBryce Scholarship",
    provider: "New York University",
    country: "United States",
    majors: ["Liberal Arts", "Business", "Economics", "Political Science", "Law"],
    amount: "Full tuition + academic enrichment stipend",
    deadline: "Jan 5, 2027",
    level: "undergraduate",
    fullRide: true,
    tags: ["need-based", "merit", "full-ride", "international-friendly", "leadership", "prestigious"],
    summary:
      "NYU's AnBryce Scholarship offers full tuition to first-generation college students, including eligible international applicants, paired with mentorship, research funding, and global learning experiences.",
  },
  {
    id: "usc-trustee",
    name: "USC Trustee Scholarship",
    provider: "University of Southern California",
    country: "United States",
    majors: ["Computer Science", "Engineering", "Business", "Design", "Architecture"],
    amount: "Full tuition (~$68,000/year)",
    deadline: "Dec 1, 2026",
    level: "undergraduate",
    fullRide: false,
    tags: ["merit", "international-friendly", "prestigious", "high-sat", "leadership"],
    summary:
      "USC's Trustee Scholarship covers full tuition for four years and is awarded to a select group of incoming freshmen, including international students, based on exceptional academic and personal achievement.",
  },
  {
    id: "amherst-finaid",
    name: "Amherst College Need-Blind International Aid",
    provider: "Amherst College",
    country: "United States",
    majors: ["Liberal Arts", "Economics", "Mathematics", "Political Science", "Environmental Science"],
    amount: "Full demonstrated need (up to ~$88,000/year)",
    deadline: "Jan 3, 2027",
    level: "undergraduate",
    fullRide: false,
    tags: ["need-based", "international-friendly", "prestigious", "high-sat"],
    summary:
      "Amherst is one of only a few U.S. liberal arts colleges that is fully need-blind for international applicants and meets 100% of demonstrated need with grant-only, loan-free financial aid packages.",
  },
  {
    id: "rhodes",
    name: "Rhodes Scholarship",
    provider: "Rhodes Trust",
    country: "United Kingdom",
    majors: ["Liberal Arts", "Political Science", "Law", "International Relations", "Economics", "Medicine"],
    amount: "Full tuition + £18,180 stipend",
    deadline: "Sep 1, 2026",
    level: "graduate",
    fullRide: true,
    tags: ["leadership", "graduate", "full-ride", "merit", "prestigious"],
    summary:
      "World's oldest international fellowship for graduate study at Oxford. Highly selective — about 100 scholars elected per year.",
  },
  {
    id: "chevening",
    name: "Chevening Scholarship",
    provider: "UK Government / FCDO",
    country: "United Kingdom",
    majors: ["International Relations", "Political Science", "Economics", "Business", "Law", "Environmental Science"],
    amount: "Full tuition + monthly stipend",
    deadline: "Nov 5, 2026",
    level: "graduate",
    fullRide: true,
    tags: ["government", "graduate", "leadership", "international-friendly", "full-ride"],
    summary:
      "UK government's global scholarship for one-year master's programs. Open to applicants from over 160 countries.",
  },
  {
    id: "gates-cambridge",
    name: "Gates Cambridge Scholarship",
    provider: "Bill & Melinda Gates Foundation",
    country: "United Kingdom",
    majors: ["Computer Science", "Engineering", "Medicine", "Mathematics", "Biology", "Physics", "Environmental Science"],
    amount: "Full cost of study",
    deadline: "Dec 3, 2026",
    level: "graduate",
    fullRide: true,
    tags: ["graduate", "full-ride", "merit", "research", "prestigious"],
    summary:
      "Full-cost scholarship for outstanding international students to pursue postgraduate study at Cambridge. ~80 awards per year.",
  },
  {
    id: "clarendon",
    name: "Clarendon Fund Scholarships",
    provider: "University of Oxford",
    country: "United Kingdom",
    majors: ["Liberal Arts", "Mathematics", "Physics", "Computer Science", "Law", "Economics", "Medicine"],
    amount: "Full fees + living grant",
    deadline: "Jan 8, 2027",
    level: "graduate",
    fullRide: true,
    tags: ["graduate", "merit", "full-ride", "research"],
    summary:
      "Oxford's flagship graduate scholarship — over 200 scholarships awarded annually to applicants of any nationality.",
  },
  {
    id: "reach-oxford",
    name: "Reach Oxford Scholarship",
    provider: "University of Oxford",
    country: "United Kingdom",
    majors: ["Liberal Arts", "Economics", "Political Science", "Mathematics", "Engineering"],
    amount: "Full tuition + £15,500/year stipend",
    deadline: "Feb 5, 2027",
    level: "undergraduate",
    fullRide: true,
    tags: ["need-based", "merit", "full-ride", "international-friendly", "high-sat", "prestigious"],
    summary:
      "Covers tuition, college fees, and living costs at Oxford for talented students from low-income countries who cannot otherwise afford an overseas education.",
  },
  {
    id: "cambridge-trust",
    name: "Cambridge Trust International Scholarship",
    provider: "Cambridge Trust",
    country: "United Kingdom",
    majors: ["Computer Science", "Engineering", "Mathematics", "Physics", "Medicine", "Law"],
    amount: "Up to £45,000/year (full cost)",
    deadline: "Dec 5, 2026",
    level: "both",
    fullRide: true,
    tags: ["merit", "full-ride", "international-friendly", "prestigious", "high-sat"],
    summary:
      "Awarded jointly with Cambridge admission, the Trust covers full tuition plus maintenance for outstanding international students across nearly every discipline.",
  },
  {
    id: "marshall",
    name: "Marshall Scholarship",
    provider: "Marshall Aid Commemoration Commission",
    country: "United Kingdom",
    majors: ["Political Science", "International Relations", "Economics", "Law", "Engineering", "Physics"],
    amount: "Full tuition + ~£18,000/year stipend",
    deadline: "Sep 29, 2026",
    level: "graduate",
    fullRide: true,
    tags: ["merit", "full-ride", "leadership", "graduate", "government", "prestigious"],
    summary:
      "Funds up to two years of graduate study at any UK university for high-achieving American students with proven leadership and academic distinction.",
  },
  {
    id: "daad",
    name: "DAAD Scholarships",
    provider: "German Academic Exchange Service",
    country: "Germany",
    majors: ["Engineering", "Computer Science", "Business", "Architecture", "Environmental Science", "Mathematics", "Physics"],
    amount: "€934/mo + tuition coverage",
    deadline: "Oct 31, 2026",
    level: "both",
    fullRide: false,
    tags: ["government", "international-friendly", "research", "stem"],
    summary:
      "Germany's largest funding organization for international students. Wide range of programs for undergrad, master's, PhD, and research stays.",
  },
  {
    id: "tu-munich-deutschland",
    name: "Deutschlandstipendium",
    provider: "TU Munich & partner universities",
    country: "Germany",
    majors: ["Engineering", "Computer Science", "Mathematics", "Physics", "Business"],
    amount: "€300/mo (no tuition needed)",
    deadline: "Apr 30, 2027",
    level: "undergraduate",
    fullRide: false,
    tags: ["merit", "stem", "international-friendly"],
    summary:
      "Merit-based monthly stipend at participating German universities. Pairs with Germany's already tuition-free public universities.",
  },
  {
    id: "humboldt-research",
    name: "Humboldt Research Fellowship",
    provider: "Alexander von Humboldt Foundation",
    country: "Germany",
    majors: ["Physics", "Biology", "Computer Science", "Engineering", "Mathematics"],
    amount: "€2,750–3,250/month + research allowance",
    deadline: "Oct 15, 2026",
    level: "graduate",
    fullRide: true,
    tags: ["merit", "full-ride", "research", "graduate", "stem", "prestigious", "language-training"],
    summary:
      "Hosts top postdoctoral researchers worldwide for 6–24 months at any German institution, with a generous monthly stipend, family allowances, and free German language training.",
  },
  {
    id: "holland",
    name: "Holland Scholarship",
    provider: "Dutch Ministry of Education",
    country: "Netherlands",
    majors: ["Business", "Engineering", "Design", "Architecture", "Economics", "Environmental Science"],
    amount: "€5,000 (one-time)",
    deadline: "Feb 1, 2027",
    level: "both",
    fullRide: false,
    tags: ["government", "international-friendly", "merit"],
    summary:
      "One-time award for non-EEA international students starting at participating Dutch research universities or universities of applied sciences.",
  },
  {
    id: "erasmus-mundus-jmd",
    name: "Erasmus Mundus Joint Masters",
    provider: "European Commission",
    country: "Netherlands",
    majors: ["Computer Science", "Environmental Science", "Engineering", "International Relations", "Economics"],
    amount: "€1,400/month + tuition + travel",
    deadline: "Jan 15, 2027",
    level: "graduate",
    fullRide: true,
    tags: ["merit", "full-ride", "international-friendly", "research", "graduate", "government", "prestigious"],
    summary:
      "Two-year master's programs delivered jointly by consortia of European universities, with full tuition, monthly stipend, and travel allowance for top global applicants.",
  },
  {
    id: "ethz-excellence",
    name: "ETH Excellence Scholarship",
    provider: "ETH Zurich",
    country: "Switzerland",
    majors: ["Engineering", "Computer Science", "Mathematics", "Physics", "Architecture", "Environmental Science"],
    amount: "CHF 12,000/sem + tuition waiver",
    deadline: "Dec 15, 2026",
    level: "graduate",
    fullRide: true,
    tags: ["merit", "graduate", "stem", "research", "full-ride"],
    summary:
      "Full grant covering living and study expenses for outstanding master's students at ETH Zurich. Highly selective — top 5% of applicants.",
  },
  {
    id: "epfl-excellence",
    name: "EPFL Excellence Fellowships",
    provider: "École polytechnique fédérale de Lausanne",
    country: "Switzerland",
    majors: ["Engineering", "Computer Science", "Mathematics", "Physics", "Architecture"],
    amount: "CHF 16,000/yr + tuition",
    deadline: "Dec 15, 2026",
    level: "graduate",
    fullRide: false,
    tags: ["merit", "graduate", "stem", "research"],
    summary:
      "Merit-based fellowship for incoming master's students at EPFL. Awarded to candidates with outstanding academic records.",
  },
  {
    id: "eiffel-excellence",
    name: "Eiffel Excellence Scholarship",
    provider: "Campus France",
    country: "France",
    majors: ["Engineering", "Economics", "Law", "Political Science", "International Relations"],
    amount: "€1,181–1,700/month + travel + insurance",
    deadline: "Jan 10, 2027",
    level: "graduate",
    fullRide: false,
    tags: ["merit", "international-friendly", "graduate", "government", "prestigious"],
    summary:
      "Flagship French government award attracting top foreign master's and PhD students to French institutions, with monthly stipend, return airfare, and health coverage.",
  },
  {
    id: "swedish-institute-gp",
    name: "Swedish Institute Scholarships for Global Professionals",
    provider: "Swedish Institute",
    country: "Sweden",
    majors: ["Environmental Science", "Engineering", "Political Science", "Business", "International Relations"],
    amount: "Full tuition + SEK 12,000/month",
    deadline: "Feb 12, 2027",
    level: "graduate",
    fullRide: true,
    tags: ["merit", "full-ride", "leadership", "international-friendly", "graduate", "government"],
    summary:
      "Funds full master's studies in Sweden for emerging leaders from selected developing countries, covering tuition, living costs, insurance, and a one-time travel grant.",
  },
  {
    id: "danish-government-cultural",
    name: "Danish Government Scholarships under the Cultural Agreements",
    provider: "Danish Ministry of Higher Education and Science",
    country: "Denmark",
    majors: ["Design", "Architecture", "Liberal Arts", "Environmental Science", "Political Science"],
    amount: "DKK 8,243/month + tuition waiver",
    deadline: "Mar 1, 2027",
    level: "both",
    fullRide: false,
    tags: ["merit", "international-friendly", "government", "language-training"],
    summary:
      "Offered to students from countries with cultural agreements with Denmark, providing a monthly living stipend, tuition exemption, and access to free Danish language courses.",
  },
  {
    id: "italian-government-mae",
    name: "Italian Government MAECI Scholarship",
    provider: "Italian Ministry of Foreign Affairs",
    country: "Italy",
    majors: ["Architecture", "Design", "Liberal Arts", "Political Science", "Economics"],
    amount: "€900/month + tuition waiver",
    deadline: "Jun 9, 2026",
    level: "graduate",
    fullRide: false,
    tags: ["merit", "international-friendly", "graduate", "government", "language-training"],
    summary:
      "Supports foreign and Italian-descent students pursuing master's, PhD, or Italian language courses in Italy, with a monthly allowance, tuition exemption, and health insurance.",
  },
  {
    id: "fundacion-carolina",
    name: "Fundación Carolina Postgraduate Scholarship",
    provider: "Fundación Carolina",
    country: "Spain",
    majors: ["Economics", "Business", "Law", "International Relations", "Political Science"],
    amount: "Full tuition + €1,200/month",
    deadline: "Feb 28, 2027",
    level: "graduate",
    fullRide: true,
    tags: ["merit", "full-ride", "international-friendly", "graduate", "prestigious"],
    summary:
      "Premier Spanish award funding Latin American and select international students to complete master's programs at top Spanish universities, with full tuition, living costs, and travel.",
  },
  {
    id: "trinity-college-dublin-global",
    name: "Trinity College Dublin Global Excellence Scholarship",
    provider: "Trinity College Dublin",
    country: "Ireland",
    majors: ["Computer Science", "Business", "Engineering", "Law", "Liberal Arts"],
    amount: "€5,000–25,000/year",
    deadline: "Apr 30, 2027",
    level: "both",
    fullRide: false,
    tags: ["merit", "international-friendly", "high-sat", "prestigious"],
    summary:
      "Awarded automatically to top-ranking non-EU applicants admitted to Trinity, providing partial tuition reductions for the duration of an undergraduate or master's degree.",
  },
  {
    id: "government-of-ireland-ihea",
    name: "Government of Ireland International Education Scholarship",
    provider: "Higher Education Authority of Ireland",
    country: "Ireland",
    majors: ["Engineering", "Computer Science", "Environmental Science", "Business", "Medicine"],
    amount: "€10,000 + full tuition waiver",
    deadline: "Mar 26, 2027",
    level: "both",
    fullRide: false,
    tags: ["merit", "international-friendly", "government", "prestigious"],
    summary:
      "Competitive one-year award for non-EU/EEA students at any publicly funded Irish higher education institution, combining a full fee waiver with a €10,000 stipend.",
  },
  {
    id: "vanier",
    name: "Vanier Canada Graduate Scholarships",
    provider: "Government of Canada",
    country: "Canada",
    majors: ["Engineering", "Computer Science", "Medicine", "Biology", "Physics", "Mathematics", "Environmental Science"],
    amount: "CAD $50,000 / year × 3 yrs",
    deadline: "Nov 1, 2026",
    level: "graduate",
    fullRide: true,
    tags: ["government", "graduate", "research", "merit", "stem"],
    summary:
      "Attracts world-class doctoral students to Canadian universities. CAD $150,000 over three years for PhD studies.",
  },
  {
    id: "uoft-lester-pearson",
    name: "Lester B. Pearson International Scholarship",
    provider: "University of Toronto",
    country: "Canada",
    majors: ["Computer Science", "Engineering", "Business", "Liberal Arts", "Economics", "Medicine"],
    amount: "Full tuition + books + living",
    deadline: "Nov 30, 2026",
    level: "undergraduate",
    fullRide: true,
    tags: ["merit", "international-friendly", "full-ride", "leadership"],
    summary:
      "U of T's most prestigious undergrad award for international students. Covers tuition, books, incidental fees, and full residence support for four years.",
  },
  {
    id: "mcgill-entrance",
    name: "McGill Entrance Scholarship Program",
    provider: "McGill University",
    country: "Canada",
    majors: ["Computer Science", "Engineering", "Medicine", "Law", "Liberal Arts"],
    amount: "CAD $3,000–$12,000/year",
    deadline: "Jan 21, 2027",
    level: "undergraduate",
    fullRide: false,
    tags: ["merit", "high-sat", "international-friendly", "prestigious"],
    summary:
      "McGill's flagship merit awards for top first-year entrants — one-time entrance prizes to renewable major scholarships covering a substantial share of tuition for standout SAT and IB performers.",
  },
  {
    id: "ubc-ilot",
    name: "International Leader of Tomorrow Award",
    provider: "University of British Columbia",
    country: "Canada",
    majors: ["Business", "Engineering", "Environmental Science", "Political Science", "Computer Science"],
    amount: "Up to CAD $80,000/year (full need)",
    deadline: "Nov 15, 2026",
    level: "undergraduate",
    fullRide: true,
    tags: ["need-based", "merit", "leadership", "international-friendly", "full-ride", "prestigious"],
    summary:
      "UBC's signature award for international undergraduates combines demonstrated financial need with superior academic achievement and leadership, covering tuition, fees, and living costs in Vancouver.",
  },
  {
    id: "waterloo-president",
    name: "President's Scholarship of Distinction",
    provider: "University of Waterloo",
    country: "Canada",
    majors: ["Computer Science", "Engineering", "Mathematics", "Physics"],
    amount: "CAD $2,000 + research/exchange grants",
    deadline: "Feb 1, 2027",
    level: "undergraduate",
    fullRide: false,
    tags: ["merit", "high-sat", "stem", "research", "international-friendly"],
    summary:
      "Awarded to incoming Waterloo students entering with averages of 95%+ or equivalent SAT scores, paired with a guaranteed research or international exchange experience grant during the co-op degree.",
  },
  {
    id: "australia-awards",
    name: "Australia Awards Scholarships",
    provider: "Australian Government",
    country: "Australia",
    majors: ["Engineering", "Environmental Science", "Medicine", "Business", "Economics", "Political Science"],
    amount: "Full tuition + travel + AUD $31,000 stipend",
    deadline: "Apr 30, 2027",
    level: "both",
    fullRide: true,
    tags: ["government", "full-ride", "international-friendly", "leadership"],
    summary:
      "Australian government scholarship for students from developing countries. Full tuition, return airfare, establishment allowance, and stipend.",
  },
  {
    id: "anu-chancellor",
    name: "ANU Chancellor's International Scholarship",
    provider: "Australian National University",
    country: "Australia",
    majors: ["Computer Science", "Engineering", "International Relations", "Economics", "Physics", "Mathematics"],
    amount: "AUD $25,000 per year",
    deadline: "Oct 31, 2026",
    level: "undergraduate",
    fullRide: false,
    tags: ["merit", "international-friendly", "high-sat"],
    summary:
      "Tuition fee reduction for high-achieving international undergraduates. Renewable for the duration of the degree if academic standing is maintained.",
  },
  {
    id: "sydney-india-equity",
    name: "Sydney Scholars India Equity Scholarship",
    provider: "University of Sydney",
    country: "Australia",
    majors: ["Engineering", "Business", "Architecture", "Liberal Arts", "Law"],
    amount: "AUD $40,000 (one-off)",
    deadline: "Oct 31, 2026",
    level: "undergraduate",
    fullRide: false,
    tags: ["merit", "need-based", "international-friendly", "prestigious"],
    summary:
      "A one-time tuition offset awarded to high-achieving international undergraduates joining USyd, prioritizing students whose academic records and SAT or A-Level results place them in the top tier of applicants.",
  },
  {
    id: "melbourne-international",
    name: "Melbourne International Undergraduate Scholarship",
    provider: "University of Melbourne",
    country: "Australia",
    majors: ["Liberal Arts", "Economics", "Biology", "Design", "Environmental Science"],
    amount: "AUD $10,000–full tuition",
    deadline: "Dec 31, 2026",
    level: "undergraduate",
    fullRide: true,
    tags: ["merit", "high-sat", "full-ride", "international-friendly", "prestigious"],
    summary:
      "Tiered awards for international entrants to Melbourne's signature generalist degrees, with the top band covering 100% of tuition for the full three years for applicants with exceptional SAT and entrance scores.",
  },
  {
    id: "unsw-global",
    name: "UNSW Global Academic Award",
    provider: "University of New South Wales",
    country: "Australia",
    majors: ["Engineering", "Computer Science", "Business", "Mathematics"],
    amount: "AUD $20,000/year",
    deadline: "Nov 30, 2026",
    level: "undergraduate",
    fullRide: false,
    tags: ["merit", "high-sat", "stem", "international-friendly"],
    summary:
      "Automatic consideration for high-achieving international applicants to UNSW Sydney, rewarding strong SAT, ATAR, or equivalent entry credentials with a renewable contribution toward tuition in Kensington.",
  },
  {
    id: "mext",
    name: "MEXT Scholarship",
    provider: "Japanese Government",
    country: "Japan",
    majors: ["Engineering", "Computer Science", "Mathematics", "Physics", "Architecture", "Design", "Environmental Science"],
    amount: "Full tuition + ¥117,000/mo + airfare",
    deadline: "May 31, 2027",
    level: "both",
    fullRide: true,
    tags: ["government", "full-ride", "international-friendly", "research"],
    summary:
      "Japanese government's flagship scholarship. Fully funded undergraduate, master's, and research programs at Japanese universities.",
  },
  {
    id: "todai-globe",
    name: "GlobE Scholarship for PEAK Students",
    provider: "University of Tokyo",
    country: "Japan",
    majors: ["International Relations", "Environmental Science", "Liberal Arts", "Political Science"],
    amount: "¥1,200,000/year + tuition waiver",
    deadline: "Dec 9, 2026",
    level: "undergraduate",
    fullRide: true,
    tags: ["merit", "full-ride", "international-friendly", "prestigious", "high-sat"],
    summary:
      "Awarded to top admits of UTokyo's English-medium PEAK program in Komaba, covering tuition plus a monthly stipend for students pursuing International Programs on Japan and East Asia or Environmental Sciences.",
  },
  {
    id: "kyoto-iup",
    name: "Kyoto iUP Scholarship",
    provider: "Kyoto University",
    country: "Japan",
    majors: ["Engineering", "Physics", "Biology", "Economics", "Liberal Arts"],
    amount: "Full tuition + ¥120,000/month + airfare",
    deadline: "Nov 7, 2026",
    level: "undergraduate",
    fullRide: true,
    tags: ["full-ride", "merit", "language-training", "international-friendly", "prestigious", "government"],
    summary:
      "Kyoto University's flagship International Undergraduate Program funds a six-month preparatory year of intensive Japanese followed by a full Japanese-language degree, with stipend, airfare, and tuition fully covered.",
  },
  {
    id: "waseda-tuition",
    name: "Waseda University Tuition Reduction Scholarship",
    provider: "Waseda University",
    country: "Japan",
    majors: ["Political Science", "Economics", "International Relations", "Liberal Arts", "Business"],
    amount: "50–100% tuition reduction",
    deadline: "Feb 15, 2027",
    level: "undergraduate",
    fullRide: false,
    tags: ["merit", "need-based", "international-friendly"],
    summary:
      "Pre-arrival award for international entrants to Waseda's English-track SILS, PSE, and SPSE programs in Tokyo, slashing annual tuition by half or in full based on combined academic and financial review.",
  },
  {
    id: "kgsp",
    name: "Korean Government Scholarship Program",
    provider: "Korean Government / NIIED",
    country: "South Korea",
    majors: ["Engineering", "Computer Science", "Business", "Design", "Liberal Arts", "International Relations"],
    amount: "Tuition + ₩1,000,000/mo + airfare",
    deadline: "Mar 15, 2027",
    level: "both",
    fullRide: true,
    tags: ["government", "full-ride", "international-friendly", "language-training"],
    summary:
      "Full scholarship at top Korean universities including a year of Korean language training. Competitive selection through embassies.",
  },
  {
    id: "kaist-international",
    name: "KAIST International Student Scholarship",
    provider: "KAIST",
    country: "South Korea",
    majors: ["Computer Science", "Engineering", "Mathematics", "Physics", "Biology"],
    amount: "Full tuition + ₩350,000/month",
    deadline: "Sep 30, 2026",
    level: "undergraduate",
    fullRide: true,
    tags: ["full-ride", "merit", "stem", "research", "international-friendly", "prestigious"],
    summary:
      "KAIST waives full tuition and provides a monthly living stipend to admitted international undergraduates in Daejeon, with renewal contingent on maintaining a strong GPA across the four-year STEM curriculum.",
  },
  {
    id: "asean-singapore",
    name: "ASEAN Undergraduate Scholarship (NUS)",
    provider: "National University of Singapore",
    country: "Singapore",
    majors: ["Computer Science", "Engineering", "Business", "Economics", "Mathematics", "Medicine"],
    amount: "Tuition + S$5,800 living allowance",
    deadline: "Mar 19, 2027",
    level: "undergraduate",
    fullRide: false,
    tags: ["merit", "international-friendly", "stem", "high-sat"],
    summary:
      "Tuition coverage and annual living stipend for undergraduates from ASEAN countries (excluding Singapore) admitted to NUS.",
  },
  {
    id: "ntu-nanyang",
    name: "Nanyang Scholarship",
    provider: "Nanyang Technological University",
    country: "Singapore",
    majors: ["Engineering", "Computer Science", "Business", "Design", "Environmental Science"],
    amount: "Full tuition + S$6,500/year + accommodation",
    deadline: "Mar 19, 2027",
    level: "undergraduate",
    fullRide: true,
    tags: ["full-ride", "merit", "leadership", "high-sat", "prestigious"],
    summary:
      "NTU Singapore's most prestigious undergraduate award covers tuition, an annual living allowance, hostel fees, and an overseas exchange grant for students with outstanding SATs and demonstrated leadership.",
  },
  {
    id: "hku-foundation",
    name: "HKU Foundation Entrance Scholarship",
    provider: "University of Hong Kong",
    country: "Hong Kong",
    majors: ["Medicine", "Law", "Business", "Engineering", "Architecture"],
    amount: "Up to HKD $191,000/year (full tuition)",
    deadline: "Jan 15, 2027",
    level: "undergraduate",
    fullRide: false,
    tags: ["merit", "high-sat", "international-friendly", "prestigious"],
    summary:
      "HKU's top entrance award for non-local applicants offers a full tuition waiver renewable across the degree for candidates with stellar SAT, AP, or A-Level credentials.",
  },
  {
    id: "schwarzman",
    name: "Schwarzman Scholars",
    provider: "Tsinghua University",
    country: "China",
    majors: ["Business", "Economics", "Political Science", "International Relations", "Law"],
    amount: "Full tuition + stipend + travel",
    deadline: "Sep 17, 2026",
    level: "graduate",
    fullRide: true,
    tags: ["graduate", "leadership", "full-ride", "prestigious", "international-friendly"],
    summary:
      "One-year master's in Global Affairs at Tsinghua's Schwarzman College in Beijing. Fully funded leadership program for ~150 scholars annually.",
  },
];
